import { requireOwner } from '../../lib/auth.js';
const json=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
async function ensure(env){
  await env.DB.batch([
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS agents(id TEXT PRIMARY KEY,name TEXT NOT NULL,role TEXT NOT NULL,instructions TEXT NOT NULL,proactive INTEGER NOT NULL DEFAULT 1,memory_mode TEXT NOT NULL DEFAULT 'long',permissions TEXT NOT NULL DEFAULT '{}',enabled INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS agent_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,agent_id TEXT NOT NULL,role TEXT NOT NULL,content TEXT NOT NULL,created_at TEXT NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS agent_memory(id INTEGER PRIMARY KEY AUTOINCREMENT,agent_id TEXT NOT NULL,memory_key TEXT NOT NULL,memory_value TEXT NOT NULL,importance INTEGER NOT NULL DEFAULT 5,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(agent_id,memory_key))`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS agent_tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,agent_id TEXT NOT NULL,title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',schedule TEXT,tool TEXT,payload TEXT,requires_approval INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`)
  ]);
  const now=new Date().toISOString();
  const defaults=[
    ['primary','Primary Agent','chief','Act as the owner\'s primary AI operating agent. Understand intent, coordinate specialist agents, protect cost and privacy, ask for approval before consequential external actions, and proactively surface useful next actions.',1,'long',JSON.stringify({research:true,code:true,automation:true,builder:true,externalActions:'approval'})],
    ['research','Research Agent','research','Research current information using approved search tools, compare sources, identify uncertainty, and return concise evidence-backed findings.',0,'project',JSON.stringify({research:true,externalActions:false})],
    ['developer','Developer Agent','developer','Plan, inspect, generate, debug and improve software projects. Prefer tests and reversible changes. Never expose secrets.',0,'project',JSON.stringify({code:true,builder:true,externalActions:'approval'})],
    ['automation','Automation Agent','automation','Design and execute approved scheduled or conditional workflows. Track state, retries, failures and approvals.',0,'long',JSON.stringify({automation:true,externalActions:'approval'})],
    ['builder','Product Builder','builder','Turn product requests into architecture, code, tests, repair cycles, previews and deployment-ready projects using approved tools and models.',0,'project',JSON.stringify({builder:true,code:true,research:true,externalActions:'approval'})]
  ];
  for(const d of defaults) await env.DB.prepare(`INSERT OR IGNORE INTO agents(id,name,role,instructions,proactive,memory_mode,permissions,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,1,?,?)`).bind(...d,now,now).run();
}
export async function onRequestGet({request,env}){const denied=await requireOwner(request,env);if(denied)return denied;try{await ensure(env);const r=await env.DB.prepare('SELECT id,name,role,instructions,proactive,memory_mode,permissions,enabled,created_at,updated_at FROM agents ORDER BY CASE id WHEN \'primary\' THEN 0 ELSE 1 END,name').all();return json({ok:true,agents:(r.results||[]).map(x=>({...x,permissions:JSON.parse(x.permissions||'{}')}))})}catch(e){return json({ok:false,error:String(e?.message||e)},500)}}
export async function onRequestPost({request,env}){const denied=await requireOwner(request,env);if(denied)return denied;try{await ensure(env);const b=await request.json();const id=String(b.id||crypto.randomUUID()).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,64);const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO agents(id,name,role,instructions,proactive,memory_mode,permissions,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,role=excluded.role,instructions=excluded.instructions,proactive=excluded.proactive,memory_mode=excluded.memory_mode,permissions=excluded.permissions,enabled=excluded.enabled,updated_at=excluded.updated_at`).bind(id,String(b.name||'Custom Agent').slice(0,80),String(b.role||'custom').slice(0,40),String(b.instructions||'').slice(0,12000),b.proactive?1:0,String(b.memoryMode||'project'),JSON.stringify(b.permissions||{}),b.enabled===false?0:1,now,now).run();return json({ok:true,id})}catch(e){return json({ok:false,error:String(e?.message||e)},500)}}
