import {requireOwner} from '../../lib/auth.js';
import {executeTask} from '../../lib/task-executor.js';
import {ensureAutomationSchema,parseSchedule,nextAfter} from '../../lib/automation-schedule.js';
const json=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
async function runTask(env,id){
 await ensureAutomationSchema(env);
 const task=await env.DB.prepare(`SELECT * FROM agent_tasks WHERE id=?`).bind(id).first();if(!task)throw new Error('Task not found');
 if(task.requires_approval&&task.status!=='approved')throw new Error('Approve this task before it can run');
 if(['cancelled','disabled','running'].includes(task.status))throw new Error(task.status==='running'?'This task is already running':`Task is ${task.status}`);
 const started=new Date().toISOString();
 const claim=await env.DB.prepare(`UPDATE agent_tasks SET status='running',updated_at=? WHERE id=? AND status=?`).bind(started,id,task.status).run();
 if(Number(claim.meta?.changes||0)!==1)throw new Error('This task changed state before execution. Refresh and try again.');
 const rr=await env.DB.prepare(`INSERT INTO automation_runs(task_id,status,started_at) VALUES(?,'running',?)`).bind(id,started).run(),runId=rr.meta?.last_row_id;
 try{
  const result=await executeTask(env,{...task,status:'running'});const finished=new Date(),next=nextAfter(task.recurrence,finished),status=next?(task.requires_approval?'approved':'pending'):'completed';
  await env.DB.prepare(`UPDATE automation_runs SET status='completed',finished_at=?,result=?,verified=1 WHERE id=?`).bind(finished.toISOString(),JSON.stringify(result),runId).run();
  await env.DB.prepare(`UPDATE agent_tasks SET status=?,result=?,last_run_at=?,next_run_at=?,run_count=COALESCE(run_count,0)+1,updated_at=? WHERE id=?`).bind(status,JSON.stringify(result),finished.toISOString(),next,finished.toISOString(),id).run();return {result,nextRunAt:next}
 }catch(e){const finished=new Date().toISOString(),error=String(e?.message||e);await env.DB.prepare(`UPDATE automation_runs SET status='failed',finished_at=?,error=?,verified=0 WHERE id=?`).bind(finished,error,runId).run();await env.DB.prepare(`UPDATE agent_tasks SET status='failed',result=?,last_run_at=?,failure_count=COALESCE(failure_count,0)+1,updated_at=? WHERE id=?`).bind(JSON.stringify({verified:false,error}),finished,finished,id).run();throw e}
}
export async function onRequestGet({request,env}){const d=await requireOwner(request,env);if(d)return d;await ensureAutomationSchema(env);const r=await env.DB.prepare(`SELECT * FROM agent_tasks ORDER BY id DESC LIMIT 100`).all();const h=await env.DB.prepare(`SELECT * FROM automation_runs ORDER BY id DESC LIMIT 100`).all();return json({ok:true,tasks:r.results||[],runs:h.results||[]})}
export async function onRequestPost({request,env}){const d=await requireOwner(request,env);if(d)return d;try{await ensureAutomationSchema(env);const b=await request.json();if(b.action&&b.id){const id=Number(b.id);if(b.action==='approve'){const changed=await env.DB.prepare(`UPDATE agent_tasks SET status='approved',updated_at=? WHERE id=? AND status='awaiting_approval'`).bind(new Date().toISOString(),id).run();if(Number(changed.meta?.changes||0)!==1)return json({ok:false,error:'Task is no longer waiting for approval.'},409);if(b.execute===true){const out=await runTask(env,id);return json({ok:true,id,status:out.nextRunAt?'approved':'completed',verified:true,...out})}return json({ok:true,id,status:'approved'})}if(b.action==='execute'){const out=await runTask(env,id);return json({ok:true,id,status:out.nextRunAt?'scheduled':'completed',verified:true,...out})}const allowed={cancel:'cancelled',retry:'pending',disable:'disabled'};const status=allowed[b.action];if(!status)return json({ok:false,error:'Unsupported task action'},400);const task=await env.DB.prepare(`SELECT requires_approval,status FROM agent_tasks WHERE id=?`).bind(id).first();if(!task)return json({ok:false,error:'Task not found'},404);if(task.status==='running')return json({ok:false,error:'A running task cannot be changed until it finishes.'},409);const nextStatus=b.action==='retry'&&task?.requires_approval?'awaiting_approval':status;await env.DB.prepare(`UPDATE agent_tasks SET status=?,enabled=?,updated_at=? WHERE id=?`).bind(nextStatus,b.action==='disable'?0:1,new Date().toISOString(),id).run();return json({ok:true,id,status:nextStatus})}const title=String(b.title||'').trim().slice(0,200);if(!title)return json({ok:false,error:'Task title required'},400);const now=new Date().toISOString(),approval=b.requiresApproval===false?0:1,status=approval?'awaiting_approval':'pending';const sched=parseSchedule(b.schedule||'',new Date());const r=await env.DB.prepare(`INSERT INTO agent_tasks(agent_id,title,status,schedule,tool,payload,requires_approval,created_at,updated_at,next_run_at,recurrence,enabled) VALUES(?,?,?,?,?,?,?,?,?,?,?,1)`).bind(String(b.agent||'primary'),title,status,b.schedule?String(b.schedule):null,b.tool?String(b.tool):null,JSON.stringify(b.payload||{}),approval,now,now,sched.nextRunAt,sched.recurrence).run();return json({ok:true,id:r.meta?.last_row_id,status,nextRunAt:sched.nextRunAt,recurrence:sched.recurrence,note:approval?'Task saved and waiting for your approval.':'Task queued.'})}catch(e){return json({ok:false,error:String(e?.message||e)},500)}}
