import {requireOwner} from '../../lib/auth.js';
import {googleGet,googleRequest} from '../../lib/google-oauth.js';
const json=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
const clean=s=>String(s||'').trim();
const decode=s=>{try{return decodeURIComponent(escape(atob(String(s||'').replace(/-/g,'+').replace(/_/g,'/'))))}catch{return ''}};
const b64=s=>btoa(unescape(encodeURIComponent(s))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const header=(p,n)=>p?.headers?.find(h=>String(h.name).toLowerCase()===n.toLowerCase())?.value||'';
function bodyText(p){if(!p)return '';if(p.mimeType==='text/plain'&&p.body?.data)return decode(p.body.data);for(const x of p.parts||[]){const t=bodyText(x);if(t)return t}return ''}
async function gmail(env,limit=5,q=''){
 const n=Math.max(1,Math.min(20,Number(limit)||5));const qs=new URLSearchParams({maxResults:String(n)});if(q)qs.set('q',q);
 const list=await googleGet(env,`https://gmail.googleapis.com/gmail/v1/users/me/messages?${qs}`);const messages=[];
 for(const x of list.messages||[]){const m=await googleGet(env,`https://gmail.googleapis.com/gmail/v1/users/me/messages/${x.id}?format=full`);messages.push({id:m.id,threadId:m.threadId,from:header(m.payload,'From'),to:header(m.payload,'To'),subject:header(m.payload,'Subject'),date:header(m.payload,'Date'),snippet:m.snippet||'',body:bodyText(m.payload).slice(0,4000)})}
 return messages;
}
async function sendMail(env,b){const to=clean(b.to),subject=clean(b.subject),body=clean(b.body);if(!to||!subject)return {ok:false,error:'to and subject are required'};const raw=b64(`To: ${to}\r\nSubject: ${subject}\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\n${body}`);const r=await googleRequest(env,'https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({raw})});return {ok:true,id:r.id,threadId:r.threadId}}
async function modifyMail(env,b){const id=clean(b.id);if(!id)return {ok:false,error:'message id required'};const add=Array.isArray(b.addLabelIds)?b.addLabelIds:[],remove=Array.isArray(b.removeLabelIds)?b.removeLabelIds:[];const r=await googleRequest(env,`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(id)}/modify`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({addLabelIds:add,removeLabelIds:remove})});return {ok:true,id:r.id,labelIds:r.labelIds||[]}}
async function calendar(env,days=1){const d=Math.max(1,Math.min(30,Number(days)||1)),a=new Date(),b=new Date(a.getTime()+d*86400000);const qs=new URLSearchParams({maxResults:'50',singleEvents:'true',orderBy:'startTime',timeMin:a.toISOString(),timeMax:b.toISOString()});const r=await googleGet(env,`https://www.googleapis.com/calendar/v3/calendars/primary/events?${qs}`);return (r.items||[]).map(e=>({id:e.id,summary:e.summary||'(No title)',start:e.start?.dateTime||e.start?.date,end:e.end?.dateTime||e.end?.date,location:e.location||'',description:e.description||'',status:e.status,htmlLink:e.htmlLink||''}))}
async function createEvent(env,b){const summary=clean(b.summary||b.title),start=clean(b.start),end=clean(b.end);if(!summary||!start)return {ok:false,error:'summary and start are required'};const zone=clean(b.timeZone)||'Asia/Kolkata';const startObj=b.allDay?{date:start}:{dateTime:start,timeZone:zone};const endObj=b.allDay?{date:end||start}:{dateTime:end||new Date(new Date(start).getTime()+3600000).toISOString(),timeZone:zone};const event={summary,description:clean(b.description),location:clean(b.location),start:startObj,end:endObj};if(Array.isArray(b.attendees))event.attendees=b.attendees.map(x=>({email:clean(x)})).filter(x=>x.email);const r=await googleRequest(env,'https://www.googleapis.com/calendar/v3/calendars/primary/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(event)});return {ok:true,id:r.id,htmlLink:r.htmlLink||'',status:r.status||''}}
async function drive(env,q='',limit=10){const n=Math.max(1,Math.min(50,Number(limit)||10));let query="trashed = false";if(q)query+=` and name contains '${clean(q).replace(/'/g,"\\'")}'`;const qs=new URLSearchParams({pageSize:String(n),q:query,orderBy:'modifiedTime desc',fields:'files(id,name,mimeType,modifiedTime,webViewLink,owners(displayName,emailAddress))'});const r=await googleGet(env,`https://www.googleapis.com/drive/v3/files?${qs}`);return r.files||[]}
export async function onRequestPost({request,env}){const denied=await requireOwner(request,env);if(denied)return denied;try{const b=await request.json(),tool=clean(b.tool).toLowerCase();if(tool==='gmail.latest'||tool==='gmail.search')return json({ok:true,tool,items:await gmail(env,b.limit,b.query||'')});if(tool==='gmail.send'){const r=await sendMail(env,b);return json({...r,tool},r.ok?200:400)}if(tool==='gmail.archive'){const r=await modifyMail(env,{...b,removeLabelIds:['INBOX']});return json({...r,tool},r.ok?200:400)}if(tool==='gmail.trash'){const id=clean(b.id);if(!id)return json({ok:false,error:'message id required'},400);const r=await googleRequest(env,`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(id)}/trash`,{method:'POST'});return json({ok:true,tool,id:r.id})}if(tool==='calendar.upcoming')return json({ok:true,tool,items:await calendar(env,b.days)});if(tool==='calendar.create'){const r=await createEvent(env,b);return json({...r,tool},r.ok?200:400)}if(tool==='calendar.delete'){const id=clean(b.id);if(!id)return json({ok:false,error:'event id required'},400);await googleRequest(env,`https://www.googleapis.com/calendar/v3/calendars/primary/events/${encodeURIComponent(id)}`,{method:'DELETE'});return json({ok:true,tool,id})}if(tool==='drive.search'||tool==='drive.latest')return json({ok:true,tool,items:await drive(env,b.query||'',b.limit)});return json({ok:false,error:'Unsupported tool.'},400)}catch(e){return json({ok:false,error:String(e?.message||e)},500)}}
