import {requireUser} from '../../../lib/user-auth.js';
import {ensureHopeChangeJobs,makeChangeId,buildChangePlan} from '../../../lib/hope-change-jobs.js';
const json=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
function themeApplication(text=''){
  const q=String(text).toLowerCase();
  let t={name:'HOPE Custom',bg:'#080b12',panel:'#10151f',panel2:'#151c28',text:'#f7f9ff',muted:'#8e9aaf',line:'#263247',accent:'#77d9ff',user:'#edf8ff',userText:'#071019'};
  if(/cyber|neon/.test(q))t={...t,name:'Neon Cyber',bg:'#05020a',panel:'#12091f',panel2:'#1c1030',line:'#392359',accent:'#35f4ff',user:'#ff4fd8',userText:'#130018'};
  if(/purple|violet/.test(q))t={...t,name:'Violet Intelligence',bg:'#090614',panel:'#151024',panel2:'#211638',line:'#3a2c5c',accent:'#b995ff'};
  if(/ocean|aqua|blue/.test(q))t={...t,name:'Ocean Intelligence',bg:'#03111b',panel:'#082131',panel2:'#0d2f44',line:'#164c68',accent:'#62dcff'};
  if(/forest|green|nature/.test(q))t={...t,name:'Forest Intelligence',bg:'#06110d',panel:'#0d2119',panel2:'#123226',line:'#245a44',accent:'#70e2a4'};
  if(/warm|sunset|orange|gold/.test(q))t={...t,name:'Solar Intelligence',bg:'#140a05',panel:'#25140c',panel2:'#352012',line:'#654127',accent:'#ffb65c'};
  if(/light|minimal|clean|white/.test(q))t={...t,name:'Clean Intelligence',bg:'#f5f8fb',panel:'#ffffff',panel2:'#eef4f8',text:'#13202b',muted:'#62717d',line:'#d6e1e8',accent:'#187da5',user:'#172633',userText:'#ffffff'};
  if(/red|crimson/.test(q))t={...t,name:'Crimson Intelligence',bg:'#100506',panel:'#200b0e',panel2:'#301116',line:'#5a252d',accent:'#ff697a'};
  return {type:'theme',...t};
}
export async function onRequestGet({request,env}){const a=await requireUser(request,env);if(a.response)return a.response;await ensureHopeChangeJobs(env);const r=await env.DB.prepare(`SELECT id,scope,target_id,request_text,change_kind,status,plan_json,requires_confirmation,created_at,updated_at FROM hope_change_jobs WHERE user_id=? ORDER BY updated_at DESC LIMIT 30`).bind(a.user.id).all();return json({ok:true,jobs:(r.results||[]).map(x=>({...x,plan:JSON.parse(x.plan_json||'{}')}))})}
export async function onRequestPost({request,env}){const a=await requireUser(request,env);if(a.response)return a.response;await ensureHopeChangeJobs(env);const b=await request.json().catch(()=>({})),text=String(b.request||'').trim().slice(0,3000),scope=['user','project','workspace'].includes(b.scope)?b.scope:'user',targetId=b.targetId?String(b.targetId).slice(0,200):null;if(!text)return json({ok:false,error:'Describe the change you want HOPE to make.'},400);const plan=buildChangePlan({text,scope,targetId}),id=makeChangeId(),t=new Date().toISOString(),application=scope==='user'&&plan.kind==='personalization'?themeApplication(text):null,status=plan.requiresConfirmation?'awaiting_confirmation':'ready';await env.DB.prepare(`INSERT INTO hope_change_jobs(id,user_id,scope,target_id,request_text,change_kind,status,plan_json,requires_confirmation,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(id,a.user.id,scope,targetId,text,plan.kind,status,JSON.stringify({...plan,application}),plan.requiresConfirmation?1:0,t,t).run();return json({ok:true,id,status,plan:{...plan,application},application,message:plan.requiresConfirmation?'HOPE prepared a reversible change plan. Preview/test it before approving application.':'HOPE prepared a reversible personal change that can be applied without affecting other users.'})}
