import {requireUser} from '../../../lib/user-auth.js';
import {consume} from '../../../lib/saas-entitlements.js';
import {executeZeroCost} from '../../../lib/router-execute.js';
import {classifyIntent} from '../../../lib/hope3-orchestrator.js';
import {autonomousResearch,researchContext} from '../../../lib/hope3-research.js';
import {userToolContext} from '../../../lib/user-tool-context.js';
const json=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
const MOODS={normal:'Respond naturally, clearly and directly.',happy:'Sound upbeat, warm and energetic. Use light humor when it fits.',funny:'Be genuinely funny in casual conversation while staying useful and accurate. Do not joke about serious or consequential matters.',angry:'Use a fiery, impatient, sharp-witted tone without insulting, threatening, demeaning or abusing anyone.'};
const moodOf=v=>MOODS[String(v||'normal').toLowerCase()]?String(v||'normal').toLowerCase():'normal';
async function ensure(env){await env.DB.batch([
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_hope_threads(id TEXT NOT NULL,user_id TEXT NOT NULL,title TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(user_id,id))`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_hope_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL,thread_id TEXT NOT NULL DEFAULT 'legacy',role TEXT NOT NULL,content TEXT NOT NULL,attachments TEXT NOT NULL DEFAULT '[]',created_at TEXT NOT NULL)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_hope_memory(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL,content TEXT NOT NULL,importance INTEGER NOT NULL DEFAULT 5,created_at TEXT NOT NULL)`)
 ]);for(const sql of [`ALTER TABLE user_hope_messages ADD COLUMN thread_id TEXT NOT NULL DEFAULT 'legacy'`,`ALTER TABLE user_hope_messages ADD COLUMN attachments TEXT NOT NULL DEFAULT '[]'`]){try{await env.DB.prepare(sql).run()}catch{}}}
async function ensureThread(env,userId,id,title='New chat'){const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO user_hope_threads(id,user_id,title,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(user_id,id) DO UPDATE SET updated_at=excluded.updated_at`).bind(id,userId,title.slice(0,80),now,now).run()}
async function recent(env,userId,threadId){const r=await env.DB.prepare(`SELECT role,content FROM user_hope_messages WHERE user_id=? AND thread_id=? ORDER BY id DESC LIMIT 24`).bind(userId,threadId).all();return (r.results||[]).reverse()}
async function memories(env,userId,q){const words=[...new Set(String(q).toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(x=>x.length>3))].slice(0,12);if(!words.length)return[];const r=await env.DB.prepare(`SELECT content,importance FROM user_hope_memory WHERE user_id=? ORDER BY importance DESC,id DESC LIMIT 120`).bind(userId).all();return (r.results||[]).map(x=>({...x,score:words.filter(w=>String(x.content).toLowerCase().includes(w)).length})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,6)}
export async function onRequestGet({request,env}){const a=await requireUser(request,env);if(a.response)return a.response;await ensure(env);const u=new URL(request.url),threadId=u.searchParams.get('thread');if(!threadId){const r=await env.DB.prepare(`SELECT id,title,created_at,updated_at FROM user_hope_threads WHERE user_id=? ORDER BY updated_at DESC LIMIT 50`).bind(a.user.id).all();return json({ok:true,user:a.user,threads:r.results||[],moods:Object.keys(MOODS)})}const r=await env.DB.prepare(`SELECT id,role,content,attachments,created_at FROM user_hope_messages WHERE user_id=? AND thread_id=? ORDER BY id LIMIT 120`).bind(a.user.id,threadId).all();return json({ok:true,user:a.user,threadId,messages:(r.results||[]).map(x=>({...x,attachments:JSON.parse(x.attachments||'[]')})),moods:Object.keys(MOODS)})}
export async function onRequestDelete({request,env}){const a=await requireUser(request,env);if(a.response)return a.response;await ensure(env);const u=new URL(request.url),threadId=u.searchParams.get('thread');if(threadId){await env.DB.batch([env.DB.prepare(`DELETE FROM user_hope_messages WHERE user_id=? AND thread_id=?`).bind(a.user.id,threadId),env.DB.prepare(`DELETE FROM user_hope_threads WHERE user_id=? AND id=?`).bind(a.user.id,threadId)]);return json({ok:true,deleted:true,threadId,memoryPreserved:true})}await env.DB.prepare(`DELETE FROM user_hope_messages WHERE user_id=?`).bind(a.user.id).run();await env.DB.prepare(`DELETE FROM user_hope_threads WHERE user_id=?`).bind(a.user.id).run();return json({ok:true,deleted:true,all:true,memoryPreserved:true})}
export async function onRequestPatch({request,env}){const a=await requireUser(request,env);if(a.response)return a.response;await ensure(env);const b=await request.json().catch(()=>({})),threadId=String(b.threadId||''),title=String(b.title||'').trim().slice(0,80);if(!threadId||!title)return json({ok:false,error:'threadId and title required'},400);await env.DB.prepare(`UPDATE user_hope_threads SET title=?,updated_at=? WHERE user_id=? AND id=?`).bind(title,new Date().toISOString(),a.user.id,threadId).run();return json({ok:true,threadId,title})}
export async function onRequestPost({request,env}){const a=await requireUser(request,env);if(a.response)return a.response;await ensure(env);const quota=await consume(env,a.user,'hope_daily',1);if(!quota.ok)return json({ok:false,error:'Daily HOPE limit reached for your plan.',usage:quota,upgrade:true},429);const b=await request.json().catch(()=>({})),text=String(b.message||'').trim().slice(0,30000),mood=moodOf(b.mood),threadId=String(b.threadId||crypto.randomUUID()).slice(0,80),attachments=(Array.isArray(b.attachments)?b.attachments:[]).slice(0,8).map(x=>({name:String(x.name||'file').slice(0,120),type:String(x.type||''),size:Number(x.size||0)}));if(!text&&!attachments.length)return json({ok:false,error:'Message or attachment required'},400);const prompt=text||`Please help me with the attached file${attachments.length>1?'s':''}: ${attachments.map(x=>x.name).join(', ')}`;const now=new Date().toISOString();await ensureThread(env,a.user.id,threadId,prompt.slice(0,64));await env.DB.prepare(`INSERT INTO user_hope_messages(user_id,thread_id,role,content,attachments,created_at) VALUES(?,?,?,?,?,?)`).bind(a.user.id,threadId,'user',prompt,JSON.stringify(attachments),now).run();const intent=classifyIntent(prompt),toolContext=await userToolContext(request,env),needsMemory=intent.primary.name==='memory'||intent.secondary.some(x=>x.name==='memory'),mem=needsMemory?await memories(env,a.user.id,prompt):[];
if(intent.primary.name==='research'){const rq=await consume(env,a.user,'research_daily',1);if(!rq.ok)return json({ok:false,error:'Daily research limit reached for your plan.',usage:rq,upgrade:true},429);const research=await autonomousResearch(prompt,{maxSources:5});if(research.ok){const r=await executeZeroCost(env,[{role:'system',content:`You are HOPE, a general-purpose AI assistant. Use ONLY the supplied live sources for current factual claims. Cite [1], [2], etc. Mood: ${mood}. ${MOODS[mood]}`},{role:'user',content:`Question: ${prompt}\n\nLIVE SOURCES:\n${researchContext(research)}`}],'hard');if(r.ok){const answer=String(r.text||'').trim();await env.DB.prepare(`INSERT INTO user_hope_messages(user_id,thread_id,role,content,created_at) VALUES(?,?,?,?,?)`).bind(a.user.id,threadId,'assistant',answer,new Date().toISOString()).run();return json({ok:true,threadId,text:answer,mood,research:true,verified:true,sources:research.sources.map(({id,title,url,engine})=>({id,title,url,engine})),provider:r.provider,model:r.model,usage:quota})}}}
if(/\b(remember|my name|i prefer|always|never|my project|my goal)\b/i.test(prompt))await env.DB.prepare(`INSERT INTO user_hope_memory(user_id,content,importance,created_at) VALUES(?,?,?,?)`).bind(a.user.id,prompt,8,now).run();const history=await recent(env,a.user.id,threadId),memoryText=mem.length?mem.map(x=>x.content).join('\n'):'No relevant personal memory.';const connected=toolContext.connectors.length?toolContext.connectors.map(x=>`${x.name}: ${x.capabilities.join(', ')}`).join('; '):'None';const attachmentContext=attachments.length?` Attached file metadata: ${attachments.map(x=>`${x.name} (${x.type||'unknown'}, ${x.size} bytes)`).join('; ')}. Do not claim to have read file contents unless file content was actually supplied.`:'';const system=`You are HOPE, a general-purpose AI assistant. Answer any ordinary subject directly and accurately. Academy context must not affect normal chat unless the user asks about learning. Use personal memory only when relevant. Never use or mention another user's data. Connected user capabilities: ${connected}. Do not claim you executed a connector action unless an actual user-scoped tool action ran and returned evidence. Relevant user memory: ${memoryText}.${attachmentContext} Mood: ${mood}. ${MOODS[mood]}`;const r=await executeZeroCost(env,[{role:'system',content:system},...history],'normal');if(!r.ok)return json({ok:false,error:r.error,attempts:r.attempts},503);const answer=String(r.text||'').trim();await env.DB.prepare(`INSERT INTO user_hope_messages(user_id,thread_id,role,content,created_at) VALUES(?,?,?,?,?)`).bind(a.user.id,threadId,'assistant',answer,new Date().toISOString()).run();return json({ok:true,threadId,text:answer,mood,provider:r.provider,model:r.model,usage:quota,connectedCapabilities:toolContext.capabilities})}
