import {requireUser} from '../../../lib/user-auth.js';
import {consume} from '../../../lib/saas-entitlements.js';
import {executeHopeGateway} from '../../../lib/hope-gateway.js';
import {classifyIntent} from '../../../lib/hope3-orchestrator.js';
import {autonomousResearch,researchContext} from '../../../lib/hope3-research.js';
import {userToolContext} from '../../../lib/user-tool-context.js';
import {buildAgentPlan,missingActionFields} from '../../../lib/hope4-agent.js';
import {ACTIONS,executeHopeAction,summarizeActionResult} from '../../../lib/hope4-executor.js';
const json=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
const MOODS={normal:'Respond naturally, clearly and directly.',happy:'Sound upbeat, warm and energetic. Use light humor when it fits.',funny:'Be genuinely funny in casual conversation while staying useful and accurate. Do not joke about serious or consequential matters.',angry:'Use a fiery, impatient, sharp-witted tone without insulting, threatening, demeaning or abusing anyone.'};
const moodOf=v=>MOODS[String(v||'normal').toLowerCase()]?String(v||'normal').toLowerCase():'normal';
const FAST_CHAT=/^(hi+|hey+|hello+|yo|good\s+(morning|afternoon|evening)|how are you|how r u|what'?s up|whats up|nothing much|not much|thanks|thank you|ok+|okay|cool|nice)[!.? ]*$/i;
async function ensure(env){await env.DB.batch([env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_hope_threads(id TEXT NOT NULL,user_id TEXT NOT NULL,title TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(user_id,id))`),env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_hope_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL,thread_id TEXT NOT NULL DEFAULT 'legacy',role TEXT NOT NULL,content TEXT NOT NULL,attachments TEXT NOT NULL DEFAULT '[]',created_at TEXT NOT NULL`),env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_hope_memory(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL,content TEXT NOT NULL,importance INTEGER NOT NULL DEFAULT 5,created_at TEXT NOT NULL`),env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_hope_agent_runs(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,objective TEXT NOT NULL,plan TEXT NOT NULL,status TEXT NOT NULL,current_step TEXT,result TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL`)]);for(const sql of [`ALTER TABLE user_hope_messages ADD COLUMN thread_id TEXT NOT NULL DEFAULT 'legacy'`,`ALTER TABLE user_hope_messages ADD COLUMN attachments TEXT NOT NULL DEFAULT '[]'`]){try{await env.DB.prepare(sql).run()}catch{}}}
async function ensureThread(env,userId,id,title='New chat'){const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO user_hope_threads(id,user_id,title,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(user_id,id) DO UPDATE SET updated_at=excluded.updated_at`).bind(id,userId,title.slice(0,80),now,now).run()}
async function recent(env,userId,threadId){const r=await env.DB.prepare(`SELECT role,content FROM user_hope_messages WHERE user_id=? AND thread_id=? ORDER BY id DESC LIMIT 24`).bind(userId,threadId).all();return (r.results||[]).reverse()}
async function memories(env,userId,q){const words=[...new Set(String(q).toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(x=>x.length>3))].slice(0,12);if(!words.length)return[];const r=await env.DB.prepare(`SELECT content,importance FROM user_hope_memory WHERE user_id=? ORDER BY importance DESC,id DESC LIMIT 120`).bind(userId).all();return (r.results||[]).map(x=>({...x,score:words.filter(w=>String(x.content).toLowerCase().includes(w)).length})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,6)}
async function runModel(env,user,system,messages,{attachments=[],threadId=null,prompt='',intent='answer'}={}){return executeHopeGateway(env,{user,threadId,prompt,intent,system,messages,attachments})}
function diagnostics(user,result){return user?.isOwner?{provider:result.provider,model:result.model,reasoning:result.reasoning,latencyMs:result.routing?.latencyMs}:undefined}
async function saveAgentRun(env,userId,prompt,plan,status='planned',result=null){const id=crypto.randomUUID(),now=new Date().toISOString();await env.DB.prepare(`INSERT INTO user_hope_agent_runs(id,user_id,objective,plan,status,current_step,result,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(id,userId,prompt,JSON.stringify(plan),status,plan.steps[0]?.id||null,result?JSON.stringify(result).slice(0,50000):null,now,now).run();return id}
async function saveAssistant(env,userId,threadId,text){await env.DB.prepare(`INSERT INTO user_hope_messages(user_id,thread_id,role,content,created_at) VALUES(?,?,?,?,?)`).bind(userId,threadId,'assistant',text,new Date().toISOString()).run()}
export async function onRequestGet({request,env}){const a=await requireUser(request,env);if(a.response)return a.response;await ensure(env);const u=new URL(request.url),threadId=u.searchParams.get('thread');if(!threadId){const r=await env.DB.prepare(`SELECT id,title,created_at,updated_at FROM user_hope_threads WHERE user_id=? ORDER BY updated_at DESC LIMIT 50`).bind(a.user.id).all();return json({ok:true,user:a.user,threads:r.results||[],moods:Object.keys(MOODS)})}const r=await env.DB.prepare(`SELECT id,role,content,attachments,created_at FROM user_hope_messages WHERE user_id=? AND thread_id=? ORDER BY id LIMIT 120`).bind(a.user.id,threadId).all();return json({ok:true,user:a.user,threadId,messages:(r.results||[]).map(x=>({...x,attachments:JSON.parse(x.attachments||'[]')})),moods:Object.keys(MOODS)})}
export async function onRequestDelete({request,env}){const a=await requireUser(request,env);if(a.response)return a.response;await ensure(env);const u=new URL(request.url),threadId=u.searchParams.get('thread');if(threadId){await env.DB.batch([env.DB.prepare(`DELETE FROM user_hope_messages WHERE user_id=? AND thread_id=?`).bind(a.user.id,threadId),env.DB.prepare(`DELETE FROM user_hope_threads WHERE user_id=? AND id=?`).bind(a.user.id,threadId)]);return json({ok:true,deleted:true,threadId,memoryPreserved:true})}await env.DB.prepare(`DELETE FROM user_hope_messages WHERE user_id=?`).bind(a.user.id).run();await env.DB.prepare(`DELETE FROM user_hope_threads WHERE user_id=?`).bind(a.user.id).run();return json({ok:true,deleted:true,all:true,memoryPreserved:true})}
export async function onRequestPatch({request,env}){const a=await requireUser(request,env);if(a.response)return a.response;await ensure(env);const b=await request.json().catch(()=>({})),threadId=String(b.threadId||''),title=String(b.title||'').trim().slice(0,80);if(!threadId||!title)return json({ok:false,error:'threadId and title required'},400);await env.DB.prepare(`UPDATE user_hope_threads SET title=?,updated_at=? WHERE user_id=? AND id=?`).bind(title,new Date().toISOString(),a.user.id,threadId).run();return json({ok:true,threadId,title})}
export async function onRequestPost({request,env}){const a=await requireUser(request,env);if(a.response)return a.response;await ensure(env);const quota=await consume(env,a.user,'hope_daily',1);if(!quota.ok)return json({ok:false,error:"You've reached today's HOPE allowance. Your history and saved work remain available.",usage:quota,upgrade:true},429);const b=await request.json().catch(()=>({})),text=String(b.message||'').trim().slice(0,30000),mood=moodOf(b.mood),threadId=String(b.threadId||crypto.randomUUID()).slice(0,80),attachments=(Array.isArray(b.attachments)?b.attachments:[]).slice(0,4).map(x=>({name:String(x.name||'file').slice(0,120),type:String(x.type||''),size:Number(x.size||0),data:String(x.data||'').slice(0,9000000),text:String(x.text||'').slice(0,30000)}));if(!text&&!attachments.length)return json({ok:false,error:'Message or attachment required'},400);const textFiles=attachments.filter(x=>x.text).map(x=>`\n\nATTACHED ${x.name}:\n${x.text}`).join(''),prompt=(text||`Please analyze the attached file${attachments.length>1?'s':''}.`)+textFiles,storedAttachments=attachments.map(({name,type,size})=>({name,type,size})),now=new Date().toISOString();await ensureThread(env,a.user.id,threadId,prompt.slice(0,64));await env.DB.prepare(`INSERT INTO user_hope_messages(user_id,thread_id,role,content,attachments,created_at) VALUES(?,?,?,?,?,?)`).bind(a.user.id,threadId,'user',text||`Attached: ${attachments.map(x=>x.name).join(', ')}`,JSON.stringify(storedAttachments),now).run();
if(!attachments.length&&FAST_CHAT.test(prompt)){const history=await recent(env,a.user.id,threadId),r=await runModel(env,a.user,`You are HOPE. Reply conversationally and briefly. ${MOODS[mood]}`,history,{threadId,prompt,intent:'conversation'});if(r.ok){const answer=String(r.text||'').trim();await saveAssistant(env,a.user.id,threadId,answer);return json({ok:true,threadId,text:answer,mood,fastPath:true,usage:quota,diagnostics:diagnostics(a.user,r)})}}
const intent=classifyIntent(prompt),toolContext=await userToolContext(request,env),plan=buildAgentPlan(prompt,toolContext.capabilities);
if(plan.autonomous){const spec=ACTIONS[plan.action],missing=missingActionFields(plan.action,plan.payload||{}),capable=spec&&toolContext.capabilities.includes(spec.capability);if(!capable){const id=await saveAgentRun(env,a.user.id,prompt,plan,'blocked',{connectRequired:true,connector:spec?.connector});const answer=`I understand the action, but ${spec?.connector||'the required app'} is not connected with ${spec?.capability||'the required'} access. Open + → Connected apps, connect it, then ask me again.`;await saveAssistant(env,a.user.id,threadId,answer);return json({ok:true,threadId,text:answer,mood,agent:true,agentRunId:id,agentStatus:'blocked',connectRequired:true,connector:spec?.connector,capability:spec?.capability,plan,usage:quota})}if(missing.length){const id=await saveAgentRun(env,a.user.id,prompt,plan,'needs_input',{missingFields:missing,payload:plan.payload});const answer=`I can do that. I still need ${missing.join(', ')} before I can safely continue.`;await saveAssistant(env,a.user.id,threadId,answer);return json({ok:true,threadId,text:answer,mood,agent:true,agentRunId:id,agentStatus:'needs_input',needsInput:true,missingFields:missing,action:plan.action,payload:plan.payload,plan,usage:quota})}if(spec.confirmation){const id=await saveAgentRun(env,a.user.id,prompt,plan,'awaiting_confirmation',{preview:plan.payload});const answer=`I’m ready to ${plan.action.replaceAll('_',' ')}. Review the details and confirm before I change anything outside HOPE.`;await saveAssistant(env,a.user.id,threadId,answer);return json({ok:true,threadId,text:answer,mood,agent:true,agentRunId:id,agentStatus:'awaiting_confirmation',requiresConfirmation:true,action:plan.action,preview:plan.payload,plan,usage:quota})}try{const result=await executeHopeAction(request,env,plan.action,plan.payload||{}),summary=summarizeActionResult(plan.action,result),id=await saveAgentRun(env,a.user.id,prompt,plan,'completed',{verified:true,action:plan.action,summary,result});await saveAssistant(env,a.user.id,threadId,summary);return json({ok:true,threadId,text:summary,mood,agent:true,agentRunId:id,agentStatus:'completed',verified:true,action:plan.action,result,plan,usage:quota})}catch(e){const id=await saveAgentRun(env,a.user.id,prompt,plan,'failed',{verified:false,error:e.message}),answer=`I couldn't complete that action: ${e.message}`;await saveAssistant(env,a.user.id,threadId,answer);return json({ok:true,threadId,text:answer,mood,agent:true,agentRunId:id,agentStatus:'failed',verified:false,error:e.message,plan,usage:quota})}}
const needsMemory=intent.primary.name==='memory'||intent.secondary.some(x=>x.name==='memory'),mem=needsMemory?await memories(env,a.user.id,prompt):[];if(intent.primary.name==='research'&&!attachments.some(x=>x.data)){const rq=await consume(env,a.user,'research_daily',1);if(!rq.ok)return json({ok:false,error:"You've reached today's research allowance. Normal HOPE remains available.",usage:rq,upgrade:true},429);const research=await autonomousResearch(prompt,{maxSources:5});if(research.ok){const r=await runModel(env,a.user,`You are HOPE. Use ONLY supplied live sources for current factual claims. Cite [1], [2], etc. ${MOODS[mood]}`,[{role:'user',content:`Question: ${prompt}\n\nLIVE SOURCES:\n${researchContext(research)}`}],{threadId,prompt,intent:'research'});if(r.ok){const answer=String(r.text||'').trim();await saveAssistant(env,a.user.id,threadId,answer);return json({ok:true,threadId,text:answer,mood,research:true,verified:true,sources:research.sources.map(({id,title,url,engine})=>({id,title,url,engine})),usage:quota,diagnostics:diagnostics(a.user,r)})}}}if(/\b(remember|my name|i prefer|always|never|my project|my goal)\b/i.test(prompt))await env.DB.prepare(`INSERT INTO user_hope_memory(user_id,content,importance,created_at) VALUES(?,?,?,?)`).bind(a.user.id,prompt,8,now).run();const history=await recent(env,a.user.id,threadId),memoryText=mem.length?mem.map(x=>x.content).join('\n'):'No relevant personal memory.',connected=toolContext.connectors.length?toolContext.connectors.map(x=>`${x.name}: ${x.capabilities.join(', ')}`).join('; '):'None',system=`You are HOPE, a general-purpose multimodal AI assistant. Answer any ordinary subject directly and accurately. Academy context must not affect normal chat unless asked. Use personal memory only when relevant. Never expose another user's data. Connected capabilities: ${connected}. Do not claim an external action happened without execution evidence. Relevant memory: ${memoryText}. ${MOODS[mood]} If image/PDF bytes are supplied, analyze only what you can actually infer from them.`;const r=await runModel(env,a.user,system,history,{attachments,threadId,prompt,intent:intent.primary.name});if(!r.ok)return json({ok:false,error:r.error,attempts:a.user.isOwner?r.attempts:undefined},503);const answer=String(r.text||'').trim();await saveAssistant(env,a.user.id,threadId,answer);return json({ok:true,threadId,text:answer,mood,usage:quota,connectedCapabilities:toolContext.capabilities,diagnostics:diagnostics(a.user,r)})}
