import {requireUser} from '../../../lib/user-auth.js';
import {classifyIntent} from '../../../lib/hope3-orchestrator.js';
import {buildAgentPlan,actionNeedsConfirmation,missingActionFields} from '../../../lib/hope4-agent.js';
import {ACTIONS} from '../../../lib/hope4-executor.js';
import {buildJob,jobProgress,safeToAutoRun} from '../../../lib/hope5-jobs.js';
import {assessMissionAttention} from '../../../lib/hope6-attention.js';
import {ensureWorkingMemory,memoryContext} from '../../../lib/hope6-working-memory.js';
const json=(v,s=200)=>new Response(JSON.stringify(v,null,2),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
export async function onRequestGet({request,env}){const a=await requireUser(request,env);if(a.response)return a.response;const checks=[],check=(name,ok,detail='')=>checks.push({name,ok:!!ok,detail});try{
check('authenticated-user',!!a.user?.id,a.user?.isOwner?'owner':'customer');
check('general-chat-routing',classifyIntent('Explain why the sky is blue').primary.name!=='memory');check('research-routing',!!classifyIntent('Research current AI model news').primary.name);
const gs=buildAgentPlan('Search my Gmail for invoice emails',['gmail']),gd=buildAgentPlan('Send an email to sam@example.com subject: Status saying Project is ready',['gmail']),cr=buildAgentPlan('Show my calendar events today',['calendar']),cc=buildAgentPlan('Create a calendar event called Review 2026-08-14T10:00:00Z 2026-08-14T10:30:00Z',['calendar']),gr=buildAgentPlan('Read my GitHub repository Akhilsaless/AI-Hub',['repos']),gi=buildAgentPlan('Create a GitHub issue "Login bug" in Akhilsaless/AI-Hub',['issues']);
check('gmail-search-detected',gs.action==='gmail_search'&&gs.autonomous);check('gmail-send-payload',gd.action==='gmail_send'&&gd.payload.to==='sam@example.com'&&missingActionFields(gd.action,gd.payload).length===0);check('gmail-write-confirmation',gd.confirmationRequired&&actionNeedsConfirmation(gd.action));check('calendar-read-detected',cr.action==='calendar_read'&&!cr.confirmationRequired);check('calendar-create-payload',cc.action==='calendar_create'&&missingActionFields(cc.action,cc.payload).length===0);check('calendar-write-confirmation',cc.confirmationRequired);check('github-read-payload',gr.action==='github_read'&&gr.payload.repo==='Akhilsaless/AI-Hub');check('github-issue-payload',gi.action==='github_issue'&&gi.payload.repo==='Akhilsaless/AI-Hub'&&!!gi.payload.title);check('github-write-confirmation',gi.confirmationRequired);check('executor-contracts',['gmail_search','gmail_draft','gmail_send','calendar_read','calendar_create','github_read','github_issue'].every(x=>!!ACTIONS[x]));
const job=buildJob('Search my Gmail for invoice emails then reply to it',['gmail']);check('multistep-job',job.steps.length>=3&&job.steps.some(x=>x.local)&&job.steps.some(x=>x.dependsOn?.length));check('job-write-protected',job.steps.some(x=>x.confirmationRequired)&&!safeToAutoRun(job.steps.find(x=>x.confirmationRequired)));check('job-progress-contract',jobProgress(job).total===job.steps.length);check('missing-input-guard',missingActionFields(buildAgentPlan('Send an email',['gmail']).action,buildAgentPlan('Send an email',['gmail']).payload).length>0);
const approval=assessMissionAttention({status:'awaiting_confirmation'},[]),failure=assessMissionAttention({status:'failed'},[]),same=assessMissionAttention({status:'completed',steps:[{status:'completed',summary:'Checked inbox and found no new important messages'}]},[{content:'Checked inbox and found no new important messages'}]);check('attention-approval-always-surfaces',approval.notify&&approval.priority===10);check('attention-failure-surfaces',failure.notify&&failure.priority>=9);check('attention-routine-suppressed',!same.notify&&same.type==='routine_no_change');check('memory-context-contract',memoryContext([{content:'Previous useful outcome'}]).includes('Previous useful outcome'));
await env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_hope_threads(id TEXT NOT NULL,user_id TEXT NOT NULL,title TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(user_id,id))`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_hope_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL,thread_id TEXT NOT NULL DEFAULT 'legacy',role TEXT NOT NULL,content TEXT NOT NULL,attachments TEXT NOT NULL DEFAULT '[]',created_at TEXT NOT NULL)`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_hope_memory(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL,content TEXT NOT NULL,importance INTEGER NOT NULL DEFAULT 5,created_at TEXT NOT NULL)`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_hope_agent_runs(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,objective TEXT NOT NULL,plan TEXT NOT NULL,status TEXT NOT NULL,current_step TEXT,result TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_hope_inbox(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,type TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'unread',priority INTEGER NOT NULL DEFAULT 5,mission_id TEXT,run_id TEXT,action TEXT,created_at TEXT NOT NULL,read_at TEXT,resolved_at TEXT)`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_hope_missions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,title TEXT NOT NULL,objective TEXT NOT NULL,schedule TEXT NOT NULL,recurrence TEXT,next_run_at TEXT,status TEXT NOT NULL DEFAULT 'active',approval_mode TEXT NOT NULL DEFAULT 'writes',enabled INTEGER NOT NULL DEFAULT 1,last_run_at TEXT,run_count INTEGER NOT NULL DEFAULT 0,failure_count INTEGER NOT NULL DEFAULT 0,last_result TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`).run();await ensureWorkingMemory(env);check('conversation-storage',true);check('agent-audit-storage',true);check('mission-storage',true);check('attention-inbox-storage',true);check('working-memory-storage',true);
const failed=checks.filter(x=>!x.ok);return json({ok:!failed.length,release:'HOPE Phase 6 production gate',version:'6.6',summary:{passed:checks.length-failed.length,total:checks.length,failed:failed.length},checks,safety:{externalWritesExecuted:false,reason:'This gate validates planning, isolation, persistence and approval contracts without sending email, creating calendar events, or creating GitHub issues.'},manualProductionChecks:['Normal chat returns a useful response instead of HTTP 500','Voice input transcribes once and sends once','Voice reply speaks once when enabled','Attention Inbox badge matches unread count','Approval item opens the paused mission','Approve continues the same run; reject performs no external side effect','Mission pause/enable does not bypass awaiting approval','Connected-account read actions return verified results','External writes happen only after explicit confirmation','Mobile composer, + menu, Inbox, Jobs and Missions remain usable'],failed:failed.map(x=>x.name)},failed.length?503:200)}catch(e){return json({ok:false,release:'HOPE Phase 6 production gate',version:'6.6',checks,error:String(e?.message||e)},500)}}
