import {CURRICULUM,curriculumActivities} from './academy-curriculum.js';
const activities=curriculumActivities();
const moduleMap=new Map(CURRICULUM.map(m=>[m.id,{...m,levelTitle:m.levelId?.[0]?.toUpperCase()+m.levelId?.slice(1)}]));
const focusByTrack={
foundations:'understand the concept, recognize its limits, and use it safely in everyday AI work',models:'compare model capabilities and choose the right model for the task instead of following hype',work:'apply AI to a realistic work problem and verify the result before using it',builder:'build the workflow step by step, understand each component, and test failure cases',
'agent-engineer':'engineer a reliable system with observability, evaluation, security and recovery paths',business:'connect AI capability to a valuable customer problem, measurable outcome and sustainable economics'};
const practiceByType={concept:'Explain the idea back in your own words, then give one correct use and one misuse.',demo:'Reproduce the demonstrated workflow with a different example and compare the result.',practice:'Complete the task yourself. Record your input, output, verification method and one improvement.',lab:'Run the lab as an experiment: form a prediction, test it, record the result and explain what changed.',quiz:'Answer without notes, then explain why each rejected option is weaker.',challenge:'Solve the scenario under the stated constraints and defend your choices.',project:'Build the deliverable, test it against the rubric and revise at least once.',assessment:'Demonstrate the skill independently. Passing requires both correctness and explanation.',capstone:'Combine the level skills into one portfolio-ready deliverable and document your decisions.',lesson:'Explain the concept in your own words, apply it to one example, and verify the result.',story:'Retell the core idea, then connect it to one real AI task.',interactive:'Complete the interaction and explain the decision you made.',mission:'Complete the scenario and document your choices and verification.',build:'Build the requested artifact, test it, and record one improvement.',battle:'Compare alternatives and defend the winner for the stated use case.',arena:'Compare the model or approach against at least one alternative.',game:'Complete the challenge and explain what signal helped you decide.',boss:'Complete the final assessment independently and defend the result.'};
const verificationByLevel={beginner:['Can I explain this without jargon?','Did I check important facts or outputs?','Do I know when not to use this technique?'],intermediate:['Does the workflow solve the stated problem?','Did I compare at least one alternative?','Can another person reproduce my result?'],advanced:['What are the failure modes and recovery paths?','How will quality, latency and cost be measured?','What security, privacy and evaluation controls are required?']};
function objective(a){const verb=a.type==='concept'?'Explain':a.type==='demo'?'Demonstrate':a.type==='quiz'||a.type==='assessment'||a.type==='boss'?'Prove mastery of':a.type==='project'||a.type==='capstone'||a.type==='build'?'Build and defend':'Apply';return `${verb} ${a.title.toLowerCase()} so you can ${focusByTrack[a.trackId]||'use the skill correctly in a real situation'}.`;}
function explanation(a,m){return `${a.title} is part of “${m?.title||a.moduleTitle}”. This activity is not a click-through lesson: learn the idea, see how it behaves in practice, then use it yourself. Focus on decisions and trade-offs, not memorizing product names. AI systems change quickly, so durable skills—clear goals, context, verification, evaluation and safe handling of data—matter more than any single interface.`;}
function example(a){const examples={foundations:'Take a vague request and improve it by adding goal, context, constraints and the required output format.',models:'Give the same task to two model approaches, score the outputs for accuracy/usefulness and explain which you would choose.',work:'Use AI on a realistic document, research or data task, then independently verify the high-impact claims.',builder:'Sketch the input → model/tool → validation → output flow and identify where the workflow can fail.','agent-engineer':'Define success metrics, tool permissions, memory boundaries, evaluation cases and a recovery path before increasing autonomy.',business:'Start with a customer pain, define the measurable result, estimate delivery cost and only then decide where AI belongs.'};return examples[a.trackId]||`Apply ${a.title} to a realistic scenario and explain your choices.`;}
export function contentFor(id){const a=activities.find(x=>x.id===id);if(!a)return null;const m=moduleMap.get(a.moduleId);return {version:2,levelId:a.levelId,moduleId:a.moduleId,moduleTitle:m?.title||a.moduleTitle,title:a.title,type:a.type,estimatedMinutes:a.minutes,objective:objective(a),explanation:explanation(a,m),keyIdeas:[`Know what “${a.title}” is meant to achieve.`,`Use the technique in context rather than as an isolated trick.`,`Verify important outputs and be able to explain your decision.`],workedExample:example(a),practice:{instruction:practiceByType[a.type]||practiceByType.practice,evidence:['Your input or approach','The resulting output/deliverable','How you checked it','What you changed after review']},mastery:{passScore:a.levelId==='beginner'?80:a.levelId==='intermediate'?85:88,checks:verificationByLevel[a.levelId]},reflection:'What would make your result fail in a real situation, and how would you detect that failure?',tutorPrompts:[`Teach me ${a.title} using an example from my goal.`,`Challenge my understanding of ${a.title}; do not give me the answer immediately.`,`Review my work for ${a.title} against the mastery checks.`],capstone:a.capstone};}
export function contentStats(){const all=activities.map(a=>contentFor(a.id));return {activities:all.length,withObjectives:all.filter(x=>x.objective).length,withPractice:all.filter(x=>x.practice?.evidence?.length>=4).length,withMastery:all.filter(x=>x.mastery?.checks?.length>=3).length,estimatedMinutes:activities.reduce((n,a)=>n+a.minutes,0)};}
