export const TRACKS=[
{id:'foundations',title:'AI Foundations',icon:'🧠',level:'Beginner',xp:900,desc:'Understand AI without drowning in jargon.',lessons:[['ai-in-10','AI in 10 minutes','story'],['prompt-battle','Prompt Battle','battle'],['hallucination-hunt','Hallucination Hunt','game'],['context-window','The Context Window','interactive'],['multimodal','AI Can See & Hear','lab'],['reasoning','How Reasoning Models Think','story']]},
{id:'models',title:'Model Arena',icon:'⚔️',level:'Beginner → Pro',xp:1400,desc:'Learn the major AI families by making them compete.',lessons:[['openai','OpenAI & GPT','arena'],['gemini','Google Gemini','arena'],['claude','Anthropic Claude','arena'],['llama','Meta Llama','arena'],['deepseek','DeepSeek','arena'],['qwen','Qwen','arena'],['mistral','Mistral','arena'],['grok','xAI Grok','arena'],['kimi','Kimi','arena'],['glm','GLM','arena'],['minimax','MiniMax','arena']]},
{id:'work',title:'AI at Work',icon:'⚡',level:'Intermediate',xp:1600,desc:'Turn everyday work into superpowers.',lessons:[['research','Research 10× faster','mission'],['docs','Documents & PDFs','lab'],['sheets','AI + spreadsheets','lab'],['sales','Sales copilot','mission'],['marketing','Marketing machine','mission'],['recruiting','Recruiting workflows','mission'],['finance','Finance workflows','mission']]},
{id:'builder',title:'AI Builder',icon:'🛠️',level:'Intermediate',xp:2200,desc:'Stop consuming AI. Build with it.',lessons:[['apis','APIs without fear','interactive'],['rag','Build RAG','build'],['agents','Build your first agent','build'],['mcp','Tools & MCP','build'],['automation','Automate a workflow','build'],['deploy','Ship an AI app','build']]},
{id:'agent-engineer',title:'Agent Engineer',icon:'🤖',level:'Advanced',xp:3000,desc:'Design reliable autonomous systems.',lessons:[['planning','Planning & decomposition','lab'],['memory','Agent memory','lab'],['tools','Tool calling','build'],['routing','Model routing','lab'],['evals','Evals & verification','mission'],['guardrails','Guardrails','mission'],['self-repair','Repair loops','build'],['multi-agent','Multi-agent systems','build']]},
{id:'business',title:'AI Business Builder',icon:'🚀',level:'Advanced',xp:2600,desc:'Turn AI ability into a real product or business.',lessons:[['problem','Find valuable problems','mission'],['economics','AI unit economics','interactive'],['mvp','Build an MVP','build'],['offer','Package the offer','mission'],['launch','Launch challenge','boss']]}
];
export const MODEL_FAMILIES=['OpenAI GPT','Google Gemini','Anthropic Claude','Meta Llama','DeepSeek','Qwen','Mistral','xAI Grok','Kimi','GLM','MiniMax','Cohere','NVIDIA NIM','OpenRouter','Hugging Face','Groq','Cerebras'];
export function allLessons(){return TRACKS.flatMap(t=>t.lessons.map((l,i)=>({id:l[0],title:l[1],format:l[2],trackId:t.id,trackTitle:t.title,index:i,xp:80+(i%3)*20})))}
export function lesson(id){return allLessons().find(x=>x.id===id)||null}
export function dailyMission(seed=new Date().toISOString().slice(0,10)){const missions=[['Spot the Fake','HOPE gives you three AI claims. Find the hallucination.','research'],['Model Duel','Solve one task with two model approaches and judge the winner.','models'],['Automate It','Take one repetitive task and design a 3-step AI automation.','builder'],['Prompt Remix','Turn a weak prompt into a professional one in under 90 seconds.','foundations'],['Agent Rescue','An agent is failing. Diagnose the reason and propose the smallest fix.','agent-engineer']];let n=0;for(const c of seed)n=(n*31+c.charCodeAt(0))>>>0;const m=missions[n%missions.length];return {id:`daily-${seed}`,title:m[0],description:m[1],track:m[2],xp:150}}
export function levelFor(xp){return Math.max(1,Math.floor(Math.sqrt(Math.max(0,xp)/180))+1)}
