import {googleGet} from './google-oauth.js';
import {loadGitHubConnector,installationToken} from './github-app.js';
async function gh(token,path){const r=await fetch(`https://api.github.com${path}`,{headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','User-Agent':'Universal-AI-Hub','X-GitHub-Api-Version':'2022-11-28'}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.message||`GitHub HTTP ${r.status}`);return j}
function hdrs(p){const a=p?.headers||[];const get=n=>a.find(h=>h.name?.toLowerCase()===n)?.value||'';return {subject:get('subject')||'(no subject)',from:get('from'),date:get('date')}}
export async function tryConnectorRead(env,text){const s=String(text||'').toLowerCase();try{
if(/\b(gmail|email|emails|inbox)\b/.test(s)&&/\b(latest|recent|subject|subjects|list|show|read)\b/.test(s)){const l=await googleGet(env,'https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=5');const out=[];for(const m of l.messages||[]){const d=await googleGet(env,`https://gmail.googleapis.com/gmail/v1/users/me/messages/${m.id}?format=metadata&metadataHeaders=Subject&metadataHeaders=From&metadataHeaders=Date`);out.push(hdrs(d.payload))}return {handled:true,tool:'gmail',verified:true,text:out.length?`Latest Gmail messages:\n${out.map((x,i)=>`${i+1}. ${x.subject}${x.from?` — ${x.from}`:''}`).join('\n')}`:'Your Gmail inbox returned no messages.'}}
if(/\b(calendar|schedule|events?|meetings?)\b/.test(s)&&/\b(today|upcoming|what|show|list)\b/.test(s)){const start=new Date(),end=new Date(start.getTime()+24*60*60*1000),u=`https://www.googleapis.com/calendar/v3/calendars/primary/events?singleEvents=true&orderBy=startTime&maxResults=10&timeMin=${encodeURIComponent(start.toISOString())}&timeMax=${encodeURIComponent(end.toISOString())}`;const j=await googleGet(env,u),items=j.items||[];return {handled:true,tool:'calendar',verified:true,text:items.length?`Calendar for the next 24 hours:\n${items.map((e,i)=>`${i+1}. ${e.summary||'(untitled)'} — ${e.start?.dateTime||e.start?.date||''}`).join('\n')}`:'No calendar events were found in the next 24 hours.'}}
if(/\b(drive|google drive|files?)\b/.test(s)&&/\b(recent|latest|show|list)\b/.test(s)){const j=await googleGet(env,'https://www.googleapis.com/drive/v3/files?pageSize=10&orderBy=modifiedTime%20desc&fields=files(id,name,mimeType,modifiedTime,webViewLink)&q=trashed%3Dfalse');const f=j.files||[];return {handled:true,tool:'drive',verified:true,text:f.length?`Recent Google Drive files accessible to HOPE:\n${f.map((x,i)=>`${i+1}. ${x.name} — modified ${x.modifiedTime||'unknown'}`).join('\n')}`:'No Drive files are currently visible through HOPE’s granted Drive scope.'}}
if(/\b(github|repositories|repos|repository)\b/.test(s)&&/\b(list|show|access|accessible|what)\b/.test(s)){const {row,app,meta}=await loadGitHubConnector(env);if(!row||!app||!meta?.installation_id)throw new Error('GitHub is not connected');const issued=await installationToken(app,meta.installation_id),j=await gh(issued.token,'/installation/repositories?per_page=100'),r=j.repositories||[];return {handled:true,tool:'github',verified:true,text:r.length?`GitHub repositories HOPE can access (${r.length}):\n${r.map((x,i)=>`${i+1}. ${x.full_name}${x.private?' [private]':''}`).join('\n')}`:'GitHub is connected, but no repositories are currently granted to HOPE.'}}
return {handled:false};
}catch(e){return {handled:true,tool:'connector',verified:false,text:`I tried the connected service, but the live check failed: ${String(e?.message||e)}`}}
}
