import {decryptStoredKey} from './vault.js';
const enc=new TextEncoder();
const b64url=bytes=>btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');
function pemBytes(pem){const b64=String(pem||'').replace(/-----BEGIN [^-]+-----/g,'').replace(/-----END [^-]+-----/g,'').replace(/\s+/g,'');return Uint8Array.from(atob(b64),c=>c.charCodeAt(0))}
function len(n){if(n<128)return Uint8Array.of(n);const a=[];while(n){a.unshift(n&255);n>>>=8}return Uint8Array.of(0x80|a.length,...a)}
function wrap(tag,body){return Uint8Array.of(tag,...len(body.length),...body)}
function concat(...parts){const n=parts.reduce((s,p)=>s+p.length,0),out=new Uint8Array(n);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function pkcs1ToPkcs8(pkcs1){const version=Uint8Array.of(0x02,0x01,0x00);const alg=Uint8Array.of(0x30,0x0d,0x06,0x09,0x2a,0x86,0x48,0x86,0xf7,0x0d,0x01,0x01,0x01,0x05,0x00);return wrap(0x30,concat(version,alg,wrap(0x04,pkcs1)))}
async function signingKey(pem){let bytes=pemBytes(pem);if(String(pem).includes('BEGIN RSA PRIVATE KEY'))bytes=pkcs1ToPkcs8(bytes);return crypto.subtle.importKey('pkcs8',bytes,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign'])}
export async function appJWT(app){const now=Math.floor(Date.now()/1000),header=b64url(enc.encode(JSON.stringify({alg:'RS256',typ:'JWT'}))),payload=b64url(enc.encode(JSON.stringify({iat:now-30,exp:now+540,iss:String(app.app_id)}))),data=`${header}.${payload}`,key=await signingKey(app.pem),sig=new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,enc.encode(data)));return `${data}.${b64url(sig)}`}
export async function githubAppRequest(app,path,init={}){const jwt=await appJWT(app),headers={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'Universal-AI-Hub',Authorization:`Bearer ${jwt}`,...(init.headers||{})};const r=await fetch(`https://api.github.com${path}`,{...init,headers});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body?.message||`GitHub HTTP ${r.status}`);return body}
export async function installationToken(app,installationId){return githubAppRequest(app,`/app/installations/${installationId}/access_tokens`,{method:'POST'})}
export async function loadGitHubConnector(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS tool_connectors(id TEXT PRIMARY KEY,label TEXT NOT NULL,key_cipher TEXT,iv TEXT,account TEXT,metadata TEXT,enabled INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL)`).run();const row=await env.DB.prepare(`SELECT * FROM tool_connectors WHERE id='github'`).first();if(!row)return {row:null,app:null,meta:{}};let app=null;try{const raw=await decryptStoredKey(env,{key_cipher:row.key_cipher,iv:row.iv});app=raw?JSON.parse(raw):null}catch{}let meta={};try{meta=JSON.parse(row.metadata||'{}')}catch{}return {row,app,meta}}
