import {encryptStoredKey,decryptStoredKey} from './vault.js';
export const GOOGLE_SCOPES=['openid','email','profile','https://www.googleapis.com/auth/gmail.modify','https://www.googleapis.com/auth/calendar.events','https://www.googleapis.com/auth/drive.readonly'];
export function origin(request){const u=new URL(request.url);return `${u.protocol}//${u.host}`}
export async function ensureGoogleTable(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS tool_connectors(id TEXT PRIMARY KEY,label TEXT NOT NULL,key_cipher TEXT,iv TEXT,account TEXT,metadata TEXT,enabled INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL)`).run()}
export async function loadGoogle(env){await ensureGoogleTable(env);const row=await env.DB.prepare(`SELECT * FROM tool_connectors WHERE id='google'`).first();if(!row)return {row:null,tokens:null,meta:{}};let tokens=null,meta={};try{tokens=JSON.parse(await decryptStoredKey(env,row)||'null')}catch{}try{meta=JSON.parse(row.metadata||'{}')}catch{}return {row,tokens,meta}}
export async function saveGoogle(env,tokens,account,meta={}){await ensureGoogleTable(env);const enc=await encryptStoredKey(env,JSON.stringify(tokens));const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO tool_connectors(id,label,key_cipher,iv,account,metadata,enabled,updated_at) VALUES('google','Google Workspace',?,?,?,?,1,?) ON CONFLICT(id) DO UPDATE SET key_cipher=excluded.key_cipher,iv=excluded.iv,account=excluded.account,metadata=excluded.metadata,enabled=1,updated_at=excluded.updated_at`).bind(enc.cipher,enc.iv,account||'',JSON.stringify(meta),now).run()}
async function refresh(env,row,tokens,meta){if(!tokens?.refresh_token)throw new Error('Google authorization expired. Reconnect Google Workspace from Connected apps.');if(!env.GOOGLE_CLIENT_ID||!env.GOOGLE_CLIENT_SECRET)throw new Error('Google OAuth configuration is incomplete.');const body=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,refresh_token:tokens.refresh_token,grant_type:'refresh_token'}),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body}),j=await r.json().catch(()=>({}));if(!r.ok){const code=String(j.error||'');if(code==='invalid_grant')throw new Error('Google authorization expired or was revoked. Reconnect Google Workspace from Connected apps.');throw new Error(j.error_description||j.error||`Google authorization refresh failed (${r.status}).`)}const next={...tokens,...j,refresh_token:tokens.refresh_token,expires_at:Date.now()+Number(j.expires_in||3600)*1000};await saveGoogle(env,next,row.account,meta);return next}
export async function accessToken(env,{forceRefresh=false}={}){const {row,tokens,meta}=await loadGoogle(env);if(!row||!tokens)throw new Error('Google Workspace is not connected. Open Connected apps to connect it.');if(!forceRefresh&&tokens.access_token&&Number(tokens.expires_at||0)>Date.now()+60000)return {token:tokens.access_token,meta,row};const next=await refresh(env,row,tokens,meta);return {token:next.access_token,meta,row}}
async function requestWithToken(token,url,init){const headers={Authorization:`Bearer ${token}`,...(init.headers||{})};return fetch(url,{...init,headers})}
export async function googleRequest(env,url,init={}){let auth=await accessToken(env),r=await requestWithToken(auth.token,url,init);if(r.status===401){auth=await accessToken(env,{forceRefresh:true});r=await requestWithToken(auth.token,url,init)}if(r.status===204)return {};const j=await r.json().catch(()=>({}));if(!r.ok){const message=j?.error?.message||j?.error_description;if(r.status===401)throw new Error('Google authorization is no longer valid. Reconnect Google Workspace from Connected apps.');if(r.status===403)throw new Error(message||'Google denied this action. Check the connected account permissions.');if(r.status===429)throw new Error('Google is temporarily rate limiting HOPE. Try again shortly.');if(r.status>=500)throw new Error('Google is temporarily unavailable. Try the action again shortly.');throw new Error(message||`Google API request failed (${r.status}).`)}return j}
export async function googleGet(env,url){return googleRequest(env,url)}
