import {ensureHope21} from './hope21-schema.js';
import {operatingContext,recordOutcome} from './hope21-intelligence.js';
const now=()=>new Date().toISOString(),uid=p=>`${p}_${crypto.randomUUID()}`;
const highRisk=a=>/(delete|purchase|payment|send|publish|production|merge|security|credential)/i.test(a||'');
export async function permissionFor(env,scope,action){await ensureHope21(env);const explicit=await env.DB.prepare(`SELECT * FROM hope_permissions WHERE enabled=1 AND scope=? AND action=? LIMIT 1`).bind(scope,action).first();if(explicit)return explicit;return {scope,action,mode:'ask_execute',risk:highRisk(action)?'high':'medium',enabled:1}}
export async function createMission(env,b){await ensureHope21(env);const t=now(),id=uid('mission'),ctx=await operatingContext(env,8);const plan=Array.isArray(b.plan)?b.plan:[];await env.DB.prepare(`INSERT INTO hope_missions(id,goal_id,title,objective,status,mode,current_step,plan,context,result,verified,retry_count,max_retries,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,0,0,?,?,?)`).bind(id,b.goal_id||null,b.title||b.objective||'HOPE mission',b.objective||'',b.status||'planned',b.mode||'ask_execute',0,JSON.stringify(plan),JSON.stringify(ctx),null,Number(b.max_retries||3),t,t).run();return id}
export async function previewStep(env,{mission_id,scope='general',action,summary='',changes='',rollback=''}){const p=await permissionFor(env,scope,action),approvalRequired=p.mode!=='autonomous'||p.risk==='high';return {mission_id,scope,action,summary,expectedChanges:changes,risk:p.risk,mode:p.mode,approvalRequired,rollbackAvailable:!!rollback,rollback}}
export async function requestApproval(env,b){await ensureHope21(env);const p=await previewStep(env,b);if(!p.approvalRequired)return {required:false,preview:p};const id=uid('approval'),t=now();await env.DB.prepare(`INSERT INTO hope_approvals(id,mission_id,scope,action,summary,risk,preview,rollback,status,created_at) VALUES(?,?,?,?,?,?,?,?, 'pending',?)`).bind(id,b.mission_id||null,b.scope||'general',b.action,b.summary||b.action,p.risk,JSON.stringify(p),b.rollback||null,t).run();if(b.mission_id)await env.DB.prepare(`UPDATE hope_missions SET status='waiting_approval',updated_at=? WHERE id=?`).bind(t,b.mission_id).run();return {required:true,approvalId:id,preview:p}}
export async function resolveApproval(env,id,status){await ensureHope21(env);if(!['approved','rejected'].includes(status))throw new Error('Invalid approval resolution');const t=now(),a=await env.DB.prepare(`SELECT * FROM hope_approvals WHERE id=?`).bind(id).first();if(!a)throw new Error('Approval not found');await env.DB.prepare(`UPDATE hope_approvals SET status=?,resolved_at=? WHERE id=?`).bind(status,t,id).run();if(a.mission_id)await env.DB.prepare(`UPDATE hope_missions SET status=?,updated_at=? WHERE id=?`).bind(status==='approved'?'planned':'blocked',t,a.mission_id).run();return a}
export async function verify(env,{mission_id=null,action,target=null,method='assertion',status,evidence=''}){await ensureHope21(env);const t=now();await env.DB.prepare(`INSERT INTO hope_verifications(mission_id,action,target,method,status,evidence,created_at) VALUES(?,?,?,?,?,?,?)`).bind(mission_id,action,target,method,status,evidence,t).run();if(mission_id&&status==='passed')await env.DB.prepare(`UPDATE hope_missions SET verified=1,updated_at=? WHERE id=?`).bind(t,mission_id).run();return {verified:status==='passed',status}}
export async function finishMission(env,{mission_id,status='completed',result='',verification=null,skill_id=null,environment=null,duration_ms=0,model=null,tool=null,cost=0}){await ensureHope21(env);const t=now();let verified=false;if(verification){const v=await verify(env,{mission_id,action:'mission_outcome',...verification});verified=v.verified}const finalStatus=status==='completed'&&!verified?'needs_verification':status;await env.DB.prepare(`UPDATE hope_missions SET status=?,result=?,verified=?,updated_at=? WHERE id=?`).bind(finalStatus,result,verified?1:0,t,mission_id).run();await recordOutcome(env,{mission_id,action:'mission',outcome:result||finalStatus,status:finalStatus==='completed'?'success':finalStatus==='failed'?'failed':'partial',verified,environment,duration_ms,skill_id,model,tool,cost});return {status:finalStatus,verified}}
export async function handleable(env){await ensureHope21(env);const loops=await env.DB.prepare(`SELECT * FROM hope_open_loops WHERE status IN ('ACTIVE','READY') ORDER BY priority DESC,last_activity LIMIT 30`).all(),missions=await env.DB.prepare(`SELECT * FROM hope_missions WHERE status IN ('planned','blocked','failed') ORDER BY updated_at LIMIT 30`).all();const executable=[],restricted=[];for(const x of loops.results||[]){const p=await permissionFor(env,'open_loop','advance');(p.mode==='autonomous'&&p.risk!=='high'?executable:restricted).push({kind:'open_loop',id:x.id,subject:x.subject,permission:p})}for(const x of missions.results||[]){const p=await permissionFor(env,'mission','advance');(p.mode==='autonomous'&&p.risk!=='high'?executable:restricted).push({kind:'mission',id:x.id,subject:x.title,permission:p})}return {executable,restricted}}
