import {classifyIntent} from './hope3-orchestrator.js';
const WRITE=new Set(['gmail_draft','gmail_send','calendar_create','github_issue']);
export function actionFromText(input){const s=String(input||'').trim(),l=s.toLowerCase();if(/\b(search|find|look for|check)\b.*\b(mail|email|gmail)\b|\b(mail|email|gmail)\b.*\b(search|find|look for|check)\b/.test(l))return 'gmail_search';if(/\b(draft|write)\b.*\b(mail|email)\b/.test(l))return 'gmail_draft';if(/\b(send|email)\b.*\b(mail|email|message)\b|^email\b/.test(l))return 'gmail_send';if(/\b(calendar|schedule|events?)\b/.test(l)&&/\b(show|check|read|what|find)\b/.test(l))return 'calendar_read';if(/\b(schedule|create|book|add)\b.*\b(meeting|event|calendar)\b/.test(l))return 'calendar_create';if(/\b(github|repo|repository)\b/.test(l)&&/\b(check|read|show|inspect)\b/.test(l))return 'github_read';if(/\b(create|open|file)\b.*\b(issue\b)/.test(l))return 'github_issue';if(/\b(hyvora|marketing|campaign)\b/.test(l)&&/\b(show|list|check|view)\b/.test(l))return 'hyvora_campaign_list';if(/\b(create|start|plan|build)\b.*\b(marketing\s+)?campaign\b|\bhyvora\b.*\b(create|start|plan|build)\b/.test(l))return 'hyvora_campaign_create';if(/\b(marketing|campaign|hyvora)\b.*\b(metrics?|analytics|performance|results)\b/.test(l))return 'hyvora_metrics_read';return null}
function email(s){return s.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0]||''}
function quoted(s){return [...s.matchAll(/["']([^"']+)["']/g)].map(x=>x[1])}
function platforms(s){const out=[];for(const p of ['instagram','youtube','facebook','linkedin','tiktok','x','twitter'])if(new RegExp(`\\b${p}\\b`,'i').test(s))out.push(p==='twitter'?'x':p);return [...new Set(out)]}
export function extractActionPayload(action,input){const s=String(input||'').trim(),q=quoted(s);if(action==='gmail_search'){const m=s.match(/(?:for|about|matching)\s+["']?(.+?)["']?$/i);return {query:(m?.[1]||s.replace(/^.*?\b(?:gmail|email|mail)\b/i,'').trim()||s),limit:10}}if(action==='gmail_draft'||action==='gmail_send'){const to=email(s),subject=q[0]||s.match(/subject\s*[:=-]\s*([^,;]+)/i)?.[1]?.trim()||'',body=q[1]||s.match(/(?:saying|say|body\s*[:=-])\s*(.+)$/i)?.[1]?.trim()||'';return {to,subject,body}}if(action==='calendar_read')return {limit:10};if(action==='calendar_create'){const iso=[...s.matchAll(/\b\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2})?(?:Z|[+-]\d{2}:?\d{2})?\b/g)].map(x=>x[0]);return {summary:q[0]||s.match(/(?:meeting|event)\s+(?:called|titled|for)\s+["']?([^"']+?)["']?(?:\s+(?:at|from|on)|$)/i)?.[1]?.trim()||'HOPE event',start:iso[0]||'',end:iso[1]||'',timeZone:''}}if(action==='github_read'||action==='github_issue'){const repo=s.match(/\b([\w.-]+\/[\w.-]+)\b/)?.[1]||'';if(action==='github_read')return {repo};const title=q[0]||s.match(/(?:issue\s+(?:called|titled|for)?\s*)["']?([^"']+?)["']?(?:\s+in\s+|\s+on\s+|$)/i)?.[1]?.trim()||s.replace(/\b(?:create|open|file|github|issue)\b/gi,' ').replace(repo,'').replace(/\s+/g,' ').trim();return {repo,title,body:q[1]||''}}if(action==='hyvora_campaign_list')return {};if(action==='hyvora_metrics_read'){const campaignId=s.match(/\b(camp_[\w-]+)\b/i)?.[1]||'';return {campaignId}}if(action==='hyvora_campaign_create'){const ps=platforms(s),name=q[0]||s.match(/campaign\s+(?:called|named|titled)\s+["']?([^"']+?)["']?(?:\s+(?:for|about|on)|$)/i)?.[1]?.trim()||'',objective=q[1]||s.match(/(?:for|objective\s*[:=-])\s+(.+?)(?:\s+on\s+(?:instagram|youtube|facebook|linkedin|tiktok|x|twitter)\b|$)/i)?.[1]?.trim()||'';return {name,objective,platforms:ps}}return {}}
export function missingActionFields(action,p={}){if(action==='gmail_draft'||action==='gmail_send')return ['to','subject','body'].filter(k=>!String(p[k]||'').trim());if(action==='calendar_create')return ['summary','start','end'].filter(k=>!String(p[k]||'').trim());if(action==='github_read')return ['repo'].filter(k=>!String(p[k]||'').trim());if(action==='github_issue')return ['repo','title'].filter(k=>!String(p[k]||'').trim());if(action==='hyvora_campaign_create'){const m=['name','objective'].filter(k=>!String(p[k]||'').trim());if(!Array.isArray(p.platforms)||!p.platforms.length)m.push('platforms');return m}return []}
export function buildAgentPlan(input,capabilities=[]){const intent=classifyIntent(input),action=actionFromText(input),payload=action?extractActionPayload(action,input):{},missingFields=action?missingActionFields(action,payload):[],steps=[];if(action)steps.push({id:'understand',type:'reason',status:'ready'},{id:'validate',type:'capability',action,status:'ready'},{id:'execute',type:'tool',action,status:'blocked',requiresConfirmation:WRITE.has(action)},{id:'verify',type:'verify',action,status:'blocked'});else steps.push({id:'understand',type:'reason',status:'ready'},{id:'respond',type:'answer',status:'blocked'});return {version:'HOPE 4.1',objective:String(input||''),intent:intent.primary.name,action,payload,missingFields,steps,autonomous:!!action,capabilities,confirmationRequired:!!action&&WRITE.has(action)}}
export function actionNeedsConfirmation(action){return WRITE.has(action)}
