import {ensureHope2} from './hope2-schema.js';
export async function ensureHope21(env){
 await ensureHope2(env);
 await env.DB.batch([
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS hope_entities(id TEXT PRIMARY KEY,entity_type TEXT NOT NULL,name TEXT NOT NULL,summary TEXT,project_id TEXT,status TEXT NOT NULL DEFAULT 'active',source TEXT,confidence REAL NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS hope_relationships(id INTEGER PRIMARY KEY AUTOINCREMENT,from_id TEXT NOT NULL,relation TEXT NOT NULL,to_id TEXT NOT NULL,confidence REAL NOT NULL DEFAULT 1,evidence TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(from_id,relation,to_id))`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS hope_open_loops(id TEXT PRIMARY KEY,subject TEXT NOT NULL,related_id TEXT,current_state TEXT,reason TEXT,next_action TEXT,dependency TEXT,priority INTEGER NOT NULL DEFAULT 3,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL,last_activity TEXT NOT NULL)`),
  env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_open_loops_status ON hope_open_loops(status,priority,last_activity)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS hope_decisions(id TEXT PRIMARY KEY,subject TEXT NOT NULL,decision TEXT NOT NULL,reason TEXT,applies_to TEXT,status TEXT NOT NULL DEFAULT 'ACTIVE',supersedes_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS hope_policies(id TEXT PRIMARY KEY,scope TEXT NOT NULL,rule TEXT NOT NULL,mode TEXT NOT NULL DEFAULT 'enforce',source TEXT NOT NULL DEFAULT 'user',status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS hope_projects(id TEXT PRIMARY KEY,name TEXT NOT NULL,goal_id TEXT,repository TEXT,environment TEXT,architecture TEXT,current_version TEXT,last_work TEXT,next_action TEXT,status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS hope_timeline(id INTEGER PRIMARY KEY AUTOINCREMENT,project_id TEXT,event_type TEXT NOT NULL,summary TEXT NOT NULL,evidence TEXT,created_at TEXT NOT NULL)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS hope_skills(id TEXT NOT NULL,version INTEGER NOT NULL,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',confidence TEXT NOT NULL DEFAULT 'EXPERIMENTAL',procedure TEXT NOT NULL,requirements TEXT NOT NULL DEFAULT '[]',validation TEXT,change_reason TEXT,evidence TEXT,created_at TEXT NOT NULL,PRIMARY KEY(id,version))`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS hope_skill_stats(skill_id TEXT PRIMARY KEY,executions INTEGER NOT NULL DEFAULT 0,successes INTEGER NOT NULL DEFAULT 0,failures INTEGER NOT NULL DEFAULT 0,partials INTEGER NOT NULL DEFAULT 0,total_duration_ms INTEGER NOT NULL DEFAULT 0,last_execution TEXT,models TEXT NOT NULL DEFAULT '{}',tools TEXT NOT NULL DEFAULT '{}',failure_patterns TEXT NOT NULL DEFAULT '{}',verification_passes INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS hope_worker_stats(worker_type TEXT NOT NULL,model TEXT NOT NULL,tasks INTEGER NOT NULL DEFAULT 0,successes INTEGER NOT NULL DEFAULT 0,failures INTEGER NOT NULL DEFAULT 0,total_duration_ms INTEGER NOT NULL DEFAULT 0,total_cost REAL NOT NULL DEFAULT 0,updated_at TEXT NOT NULL,PRIMARY KEY(worker_type,model))`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS hope_outcomes(id INTEGER PRIMARY KEY AUTOINCREMENT,mission_id TEXT,action TEXT,outcome TEXT NOT NULL,status TEXT NOT NULL,verified INTEGER NOT NULL DEFAULT 0,feedback TEXT,environment TEXT,created_at TEXT NOT NULL)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS hope_shadow_patterns(id TEXT PRIMARY KEY,signature TEXT NOT NULL,repetitions INTEGER NOT NULL DEFAULT 1,successes INTEGER NOT NULL DEFAULT 0,exceptions INTEGER NOT NULL DEFAULT 0,last_seen TEXT NOT NULL,suggested INTEGER NOT NULL DEFAULT 0,approved INTEGER NOT NULL DEFAULT 0)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS hope_cost_events(id INTEGER PRIMARY KEY AUTOINCREMENT,mission_id TEXT,path TEXT NOT NULL,provider TEXT,model TEXT,estimated_cost REAL NOT NULL DEFAULT 0,currency TEXT NOT NULL DEFAULT 'USD',created_at TEXT NOT NULL)`)
 ]);
}
