export const PROVIDER_CATALOG_VERSION='2026-08-15';

// Connection methods are deliberately conservative. `oauth` is used only where AI Hub
// has a real authorization flow. `api-key` means the provider requires a developer key.
// Offers change frequently, so `lastVerified` and `offerKind` are product data, not promises.
export const PROVIDER_CATALOG=[
 {id:'openai',name:'OpenAI API',endpoint:'https://api.openai.com/v1',connectMethod:'api-key',signupUrl:'https://platform.openai.com/api-keys',offerKind:'paid-disabled',offerLabel:'Production-primary slot · disabled until Owner enables it',lastVerified:'2026-08-15',officialUrl:'https://platform.openai.com/docs',capabilities:['chat','reasoning','code','vision','audio','image','tools'],discoverable:false,note:'Owner-only production provider. The slot can be configured now and remains disabled until billing, budgets and an explicit Owner enable action are ready.'},
 {id:'openrouter',name:'OpenRouter',endpoint:'https://openrouter.ai/api/v1',connectMethod:'oauth',connectPath:'/api/connect/openrouter/start',offerKind:'free-tier',offerLabel:'25+ free models; free router available',lastVerified:'2026-08-12',officialUrl:'https://openrouter.ai/pricing',capabilities:['chat','reasoning','code','vision','tools'],discoverable:true,note:'Best one-click source in AI Hub. Free-model availability and rate limits can change.'},
 {id:'groq',name:'Groq',endpoint:'https://api.groq.com/openai/v1',connectMethod:'api-key',signupUrl:'https://console.groq.com',offerKind:'free-tier',offerLabel:'Free plan with published per-model rate limits',lastVerified:'2026-08-12',officialUrl:'https://console.groq.com/docs/rate-limits',capabilities:['chat','reasoning','code','audio'],discoverable:true,note:'Developer API key required by Groq. AI Hub stores it encrypted.'},
 {id:'gemini',name:'Google Gemini API',endpoint:'https://generativelanguage.googleapis.com',connectMethod:'api-key',signupUrl:'https://aistudio.google.com/app/apikey',offerKind:'free-tier-variable',offerLabel:'Free tier exists for eligible models/accounts; availability is best-effort',lastVerified:'2026-08-12',officialUrl:'https://ai.google.dev/gemini-api/docs/pricing',capabilities:['chat','reasoning','code','vision','audio','files','tools'],discoverable:true,note:'Free quotas are model/account dependent and can change. API key is required.'},
 {id:'huggingface',name:'Hugging Face Inference Providers',endpoint:'https://router.huggingface.co/v1',connectMethod:'api-key',signupUrl:'https://huggingface.co/settings/tokens',offerKind:'monthly-credit',offerLabel:'Free users receive small monthly Inference Provider credits',lastVerified:'2026-08-12',officialUrl:'https://huggingface.co/docs/inference-providers/en/pricing',capabilities:['chat','code','vision','image','embeddings'],discoverable:true,note:'One Hugging Face token can route across many inference providers.'},
 {id:'googlecloud',name:'Google Cloud / Vertex AI',endpoint:'https://aiplatform.googleapis.com',connectMethod:'guided',signupUrl:'https://cloud.google.com/free',offerKind:'signup-credit',offerLabel:'New Google Cloud customers may receive $300 Welcome credit for 90 days; exclusions apply',lastVerified:'2026-08-12',officialUrl:'https://docs.cloud.google.com/free/docs/free-cloud-features',capabilities:['chat','reasoning','code','vision','image','video','audio','embeddings'],discoverable:false,note:'Google states the $300 trial has product exclusions; Gemini API in AI Studio is specifically excluded from that credit.'},
 {id:'cerebras',name:'Cerebras Inference',endpoint:'https://api.cerebras.ai/v1',connectMethod:'api-key',signupUrl:'https://cloud.cerebras.ai',offerKind:'verify-at-connect',offerLabel:'Account offer must be verified when connected',lastVerified:'2026-08-12',officialUrl:'https://inference-docs.cerebras.ai',capabilities:['chat','reasoning','code'],discoverable:true,note:'Fast inference provider. AI Hub will not classify it as zero-cost until current account/model status is verified.'},
 {id:'nvidia',name:'NVIDIA API Catalog / NIM',endpoint:'https://integrate.api.nvidia.com/v1',connectMethod:'api-key',signupUrl:'https://build.nvidia.com',offerKind:'verify-at-connect',offerLabel:'Developer access/credits vary by program and model',lastVerified:'2026-08-12',officialUrl:'https://build.nvidia.com',capabilities:['chat','reasoning','code','vision','image'],discoverable:true,note:'API key required where NVIDIA exposes hosted API access.'},
 {id:'mistral',name:'Mistral AI',endpoint:'https://api.mistral.ai/v1',connectMethod:'api-key',signupUrl:'https://console.mistral.ai',offerKind:'verify-at-connect',offerLabel:'Current trial/free availability must be verified at connection time',lastVerified:'2026-08-12',officialUrl:'https://docs.mistral.ai',capabilities:['chat','reasoning','code','vision','embeddings'],discoverable:true,note:'API key connection; AI Hub does not assume promotional access is permanent.'},
 {id:'cohere',name:'Cohere',endpoint:'https://api.cohere.com/v2',connectMethod:'api-key',signupUrl:'https://dashboard.cohere.com/api-keys',offerKind:'trial',offerLabel:'Trial/developer access may be available; verify current account quota',lastVerified:'2026-08-12',officialUrl:'https://docs.cohere.com',capabilities:['chat','reasoning','embeddings','rerank','tools'],discoverable:false,note:'Cohere uses API keys. Trial status is kept separate from permanent free-tier routing.'},
 {id:'sambanova',name:'SambaNova Cloud',endpoint:'https://api.sambanova.ai/v1',connectMethod:'api-key',signupUrl:'https://cloud.sambanova.ai',offerKind:'verify-at-connect',offerLabel:'Verify current developer credits/free quota when connected',lastVerified:'2026-08-12',officialUrl:'https://docs.sambanova.ai',capabilities:['chat','reasoning','code'],discoverable:true,note:'OpenAI-compatible API where available.'},
 {id:'together',name:'Together AI',endpoint:'https://api.together.xyz/v1',connectMethod:'api-key',signupUrl:'https://api.together.xyz/settings/api-keys',offerKind:'promo-variable',offerLabel:'Signup/promotional credits vary; verify current account offer',lastVerified:'2026-08-12',officialUrl:'https://docs.together.ai',capabilities:['chat','reasoning','code','image','embeddings'],discoverable:true,note:'API key required. Promotional credit is never treated as an always-free route.'},
 {id:'fireworks',name:'Fireworks AI',endpoint:'https://api.fireworks.ai/inference/v1',connectMethod:'api-key',signupUrl:'https://app.fireworks.ai',offerKind:'promo-variable',offerLabel:'Trial/promotional credits vary; verify at connect',lastVerified:'2026-08-12',officialUrl:'https://docs.fireworks.ai',capabilities:['chat','reasoning','code','vision','embeddings'],discoverable:true,note:'API key required.'},
 {id:'deepinfra',name:'DeepInfra',endpoint:'https://api.deepinfra.com/v1/openai',connectMethod:'api-key',signupUrl:'https://deepinfra.com/dash/api_keys',offerKind:'promo-variable',offerLabel:'Promotions can vary; verify current balance at connect',lastVerified:'2026-08-12',officialUrl:'https://deepinfra.com/docs',capabilities:['chat','reasoning','code','vision','image','embeddings'],discoverable:true,note:'OpenAI-compatible API; current free/promo status is not assumed.'},
 {id:'siliconflow',name:'SiliconFlow',endpoint:'https://api.siliconflow.com/v1',connectMethod:'api-key',signupUrl:'https://cloud.siliconflow.com',offerKind:'promo-variable',offerLabel:'Regional signup credits/promotions may vary',lastVerified:'2026-08-12',officialUrl:'https://docs.siliconflow.com',capabilities:['chat','reasoning','code','image','embeddings'],discoverable:true,note:'API key required; offers are verified per account.'},
 {id:'novita',name:'Novita AI',endpoint:'https://api.novita.ai/v3/openai',connectMethod:'api-key',signupUrl:'https://novita.ai',offerKind:'promo-variable',offerLabel:'Promotional credit may vary; verify at connect',lastVerified:'2026-08-12',officialUrl:'https://novita.ai/docs',capabilities:['chat','reasoning','code','image','video'],discoverable:true,note:'API key required.'},
 {id:'qwen',name:'Alibaba Cloud / Qwen',endpoint:'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',connectMethod:'api-key',signupUrl:'https://bailian.console.alibabacloud.com',offerKind:'promo-variable',offerLabel:'Free quota/trial offers vary by region and model',lastVerified:'2026-08-12',officialUrl:'https://www.alibabacloud.com/help/en/model-studio',capabilities:['chat','reasoning','code','vision','audio','image'],discoverable:true,note:'DashScope/Model Studio credential required.'},
 {id:'glm',name:'Z.ai / GLM',endpoint:'https://api.z.ai/api/paas/v4',connectMethod:'api-key',signupUrl:'https://z.ai',offerKind:'promo-variable',offerLabel:'Verify current signup/trial offer at connect',lastVerified:'2026-08-12',officialUrl:'https://docs.z.ai',capabilities:['chat','reasoning','code','vision'],discoverable:true,note:'API key required.'},
 {id:'kimi',name:'Kimi / Moonshot AI',endpoint:'https://api.moonshot.ai/v1',connectMethod:'api-key',signupUrl:'https://platform.moonshot.ai',offerKind:'promo-variable',offerLabel:'Verify current regional signup/trial offer at connect',lastVerified:'2026-08-12',officialUrl:'https://platform.moonshot.ai/docs',capabilities:['chat','reasoning','code','vision'],discoverable:true,note:'API key required.'},
 {id:'minimax',name:'MiniMax',endpoint:'https://api.minimax.io/v1',connectMethod:'api-key',signupUrl:'https://platform.minimax.io',offerKind:'promo-variable',offerLabel:'Verify current signup/trial offer at connect',lastVerified:'2026-08-12',officialUrl:'https://platform.minimax.io/docs',capabilities:['chat','reasoning','code','audio','image','video'],discoverable:true,note:'API key required.'},
 {id:'deepseek',name:'DeepSeek',endpoint:'https://api.deepseek.com',connectMethod:'api-key',signupUrl:'https://platform.deepseek.com/api_keys',offerKind:'paid-or-promo',offerLabel:'No permanent free API assumption; verify any account promotion',lastVerified:'2026-08-12',officialUrl:'https://api-docs.deepseek.com',capabilities:['chat','reasoning','code'],discoverable:true,note:'API key required.'},
 {id:'githubmodels',name:'GitHub Models',endpoint:'https://models.github.ai/inference',connectMethod:'guided',signupUrl:'https://github.com/marketplace/models',offerKind:'free-limited',offerLabel:'GitHub Models provides rate-limited experimentation access depending on plan/model',lastVerified:'2026-08-12',officialUrl:'https://docs.github.com/en/github-models',capabilities:['chat','reasoning','code','vision','embeddings'],discoverable:false,note:'Authentication uses GitHub credentials/tokens; can later reuse the Hub GitHub connection where scopes permit.'},
 {id:'agentrouter',name:'AgentRouter',endpoint:'https://agentrouter.org/v1',connectMethod:'api-key',signupUrl:'https://agentrouter.org',offerKind:'promo-credit',offerLabel:'Promotional credits tracked separately from permanent free models',lastVerified:'2026-08-12',officialUrl:'https://agentrouter.org',capabilities:['chat','reasoning','code'],discoverable:true,note:'Credit-backed routes are disabled from ZERO_COST routing unless explicitly qualified.'},
 {id:'omniroute',name:'OmniRoute / Custom OpenAI-compatible',endpoint:'',connectMethod:'endpoint',offerKind:'custom',offerLabel:'Bring your own public HTTPS compatible endpoint',lastVerified:'2026-08-12',officialUrl:'',capabilities:['chat'],discoverable:true,note:'For self-hosted or other legitimate OpenAI-compatible endpoints.'}
];

export function providerById(id){return PROVIDER_CATALOG.find(x=>x.id===String(id||''))||null}
