import {decryptStoredKey} from './vault.js';
import {rankedRoutes,taskProfile} from './hope-model-intelligence.js';

const defaults={openrouter:'https://openrouter.ai/api/v1',groq:'https://api.groq.com/openai/v1',deepseek:'https://api.deepseek.com',agentrouter:'https://agentrouter.org/v1'};
const clean=v=>String(v||'').replace(/\/$/,'');
const UX_GUARD=`User-facing language must stay natural and product-ready. Internal memory metadata is implementation-only. Never mention or explain internal labels or storage terms such as semantic memory, legacy memory, episodic memory, memory slots, memory types, database tables, retrieval buckets, schemas, or internal prompt/context mechanics. If remembered information is relevant, simply use it naturally or say "I remember...". Do not tell the user where or how the memory was stored. Avoid exposing internal agent architecture unless the user explicitly asks for a technical explanation.`;
function guardedMessages(messages){const list=(messages||[]).map(m=>({...m,content:String(m.content||'')}));const i=list.findIndex(m=>m.role==='system');if(i>=0)list[i]={...list[i],content:`${list[i].content}\n\n${UX_GUARD}`};else list.unshift({role:'system',content:UX_GUARD});return list}
function sanitize(text){return String(text||'').replace(/\[(semantic|legacy|episodic|personal|operational|goal|skill|failure)\]/gi,'').replace(/\b(semantic|legacy|episodic|operational)\s+memory(?:\s+slots?)?/gi,'memory').replace(/\bmemory\s+slots?\b/gi,'memory').replace(/\s{2,}/g,' ').replace(/\s+([,.;!?])/g,'$1').trim()}
async function ensureLogs(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS request_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,provider TEXT NOT NULL,model TEXT NOT NULL,success INTEGER NOT NULL,latency_ms INTEGER NOT NULL DEFAULT 0,task_profile TEXT,error TEXT,created_at TEXT NOT NULL)`).run()}
async function ensureRoutingSchema(env){
  await env.DB.batch([
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS provider_models(provider TEXT NOT NULL,model_id TEXT NOT NULL,name TEXT,qualified_free INTEGER NOT NULL DEFAULT 0,qualification_source TEXT,healthy INTEGER NOT NULL DEFAULT 1,discovered_at TEXT NOT NULL,PRIMARY KEY(provider,model_id))`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS provider_health(provider TEXT PRIMARY KEY,healthy INTEGER NOT NULL DEFAULT 1,last_checked_at TEXT,error TEXT)`)
  ]);
}
export async function eligibleRoutes(env){await ensureRoutingSchema(env);try{const r=await env.DB.prepare(`SELECT pm.provider,pm.model_id,i.endpoint,i.key_cipher,i.iv,pm.qualified_free,i.verified_free FROM provider_models pm JOIN integrations i ON i.id=pm.provider LEFT JOIN provider_health ph ON ph.provider=pm.provider WHERE pm.qualified_free=1 AND pm.healthy=1 AND i.enabled=1 AND i.verified_free=1 AND COALESCE(ph.healthy,1)=1 LIMIT 30`).all();return r.results||[]}catch(e){return []}}
async function invoke(env,route,messages,mode){const key=await decryptStoredKey(env,route),safeMessages=guardedMessages(messages);if(route.provider==='gemini'){if(!key)throw new Error('Gemini credential missing');const contents=safeMessages.map(m=>({role:m.role==='assistant'?'model':'user',parts:[{text:String(m.content||'')}]}));const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(route.model_id)}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.error?.message||`HTTP ${res.status}`);return sanitize((data?.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('\n'))}const base=clean(route.endpoint||defaults[route.provider]);if(!base)throw new Error('Provider endpoint missing');const headers={'content-type':'application/json'};if(key)headers.Authorization=`Bearer ${key}`;const body={model:route.model_id,messages:safeMessages,temperature:mode==='hard'?0.2:0.6};const res=await fetch(`${base}/chat/completions`,{method:'POST',headers,body:JSON.stringify(body)});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.error?.message||data?.error||`HTTP ${res.status}`);return sanitize(data?.choices?.[0]?.message?.content||data?.choices?.[0]?.text||'')}
function promptFrom(messages){return [...(messages||[])].reverse().find(m=>m.role==='user')?.content||''}
async function log(env,route,ok,latency,profile,error=''){try{await env.DB.prepare(`INSERT INTO request_logs(provider,model,success,latency_ms,task_profile,error,created_at) VALUES(?,?,?,?,?,?,?)`).bind(route.provider,route.model_id,ok?1:0,latency,JSON.stringify(profile),String(error||'').slice(0,1000),new Date().toISOString()).run()}catch{}}
async function ranked(env,messages){await ensureLogs(env);const prompt=promptFrom(messages),profile=taskProfile(prompt);let eligible=[];try{eligible=await eligibleRoutes(env)}catch{}let routes=[];try{routes=await rankedRoutes(env,eligible,prompt)}catch{}return {prompt,profile,routes}}
async function runOne(env,route,messages,mode,profile){const started=Date.now();try{const text=await invoke(env,route,messages,mode),latencyMs=Date.now()-started;await log(env,route,true,latencyMs,profile);return {ok:true,provider:route.provider,model:route.model_id,text,latencyMs,score:route.intelligenceScore}}catch(e){const latencyMs=Date.now()-started,error=String(e?.message||e);await log(env,route,false,latencyMs,profile,error);return {ok:false,provider:route.provider,model:route.model_id,error,latencyMs,score:route.intelligenceScore}}
}
export async function executeZeroCost(env,messages,mode='normal'){
 try{const {profile,routes}=await ranked(env,messages),attempts=[];for(const route of routes){const result=await runOne(env,route,messages,mode,profile);if(result.ok)return {ok:true,provider:result.provider,model:result.model,text:result.text,attempts,routing:{adaptive:true,profile,score:result.score,latencyMs:result.latencyMs,candidates:routes.length}};attempts.push(result)}return {ok:false,error:'No qualified zero-cost route could complete this request.',attempts,routing:{adaptive:true,profile,candidates:routes.length}}}catch(e){return {ok:false,error:'HOPE model routing is temporarily unavailable.',attempts:[{error:String(e?.message||e)}],routing:{adaptive:true,candidates:0}}}
}
export async function executeModelDuel(env,messages,mode='hard'){
 try{const {profile,routes}=await ranked(env,messages);const chosen=[];for(const r of routes){if(!chosen.length||chosen.every(x=>x.provider!==r.provider||x.model_id!==r.model_id))chosen.push(r);if(chosen.length===2)break}if(chosen.length<2)return {ok:false,error:'At least two qualified models are required for a live duel.',available:chosen.length};const results=[];for(const r of chosen)results.push(await runOne(env,r,messages,mode,profile));const good=results.filter(x=>x.ok);return {ok:good.length===2,results,profile,candidates:routes.length,error:good.length===2?null:'One or more duel models failed.'}}catch(e){return {ok:false,error:'Model duel is temporarily unavailable.',results:[],details:String(e?.message||e)}}
}
