import {decryptStoredKey} from './vault.js';
import {rankedRoutes,taskProfile} from './hope-model-intelligence.js';
const defaults={openai:'https://api.openai.com/v1',openrouter:'https://openrouter.ai/api/v1',groq:'https://api.groq.com/openai/v1',deepseek:'https://api.deepseek.com',agentrouter:'https://agentrouter.org/v1'};
const OPENAI_AUTO_MODELS={fast:'gpt-5.6-luna',normal:'gpt-5.6-terra',hard:'gpt-5.6-terra'};
const OPENAI_PRICING={
 'gpt-5.6-luna':{input:0.20,output:1.20},
 'gpt-5.6-terra':{input:2.00,output:12.00},
 'gpt-5.6-sol':{input:5.00,output:30.00},
 'gpt-5.4-mini':{input:0.75,output:4.50},
 'gpt-5.4':{input:2.50,output:15.00},
 'gpt-5-mini':{input:0.25,output:2.00}
};
const clean=v=>String(v||'').replace(/\/$/,'');
const signal=ms=>AbortSignal.timeout?AbortSignal.timeout(ms):undefined;
const UX_GUARD=`User-facing language must stay natural and product-ready. Internal memory metadata is implementation-only. Never mention or explain internal labels or storage terms such as semantic memory, legacy memory, episodic memory, memory slots, memory types, database tables, retrieval buckets, schemas, or internal prompt/context mechanics. If remembered information is relevant, simply use it naturally or say "I remember...". Do not tell the user where or how the memory was stored. Avoid exposing internal agent architecture unless the user explicitly asks for a technical explanation.`;
function guardedMessages(messages){const list=(messages||[]).map(m=>({...m,content:Array.isArray(m.content)?m.content:String(m.content||'')}));const i=list.findIndex(m=>m.role==='system');if(i>=0)list[i]={...list[i],content:`${String(list[i].content||'')}\n\n${UX_GUARD}`};else list.unshift({role:'system',content:UX_GUARD});return list}
function sanitize(text){return String(text||'').replace(/\[(semantic|legacy|episodic|personal|operational|goal|skill|failure)\]/gi,'').replace(/\b(semantic|legacy|episodic|operational)\s+memory(?:\s+slots?)?/gi,'memory').replace(/\bmemory\s+slots?\b/gi,'memory').replace(/\s{2,}/g,' ').replace(/\s+([,.;!?])/g,'$1').trim()}
async function ensureLogs(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS request_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,provider TEXT NOT NULL,model TEXT NOT NULL,success INTEGER NOT NULL,latency_ms INTEGER NOT NULL DEFAULT 0,task_profile TEXT,error TEXT,estimated_cost_usd REAL NOT NULL DEFAULT 0,input_tokens INTEGER NOT NULL DEFAULT 0,output_tokens INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL)`).run();for(const sql of [`ALTER TABLE request_logs ADD COLUMN latency_ms INTEGER NOT NULL DEFAULT 0`,`ALTER TABLE request_logs ADD COLUMN task_profile TEXT`,`ALTER TABLE request_logs ADD COLUMN error TEXT`,`ALTER TABLE request_logs ADD COLUMN estimated_cost_usd REAL NOT NULL DEFAULT 0`,`ALTER TABLE request_logs ADD COLUMN input_tokens INTEGER NOT NULL DEFAULT 0`,`ALTER TABLE request_logs ADD COLUMN output_tokens INTEGER NOT NULL DEFAULT 0`]){try{await env.DB.prepare(sql).run()}catch{}}}
async function ensureRoutingSchema(env){await env.DB.batch([env.DB.prepare(`CREATE TABLE IF NOT EXISTS provider_models(provider TEXT NOT NULL,model_id TEXT NOT NULL,name TEXT,qualified_free INTEGER NOT NULL DEFAULT 0,qualification_source TEXT,healthy INTEGER NOT NULL DEFAULT 1,discovered_at TEXT NOT NULL,PRIMARY KEY(provider,model_id))`),env.DB.prepare(`CREATE TABLE IF NOT EXISTS provider_health(provider TEXT PRIMARY KEY,healthy INTEGER NOT NULL DEFAULT 1,last_checked_at TEXT,error TEXT)`)])}
async function ensureBudgetSchema(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS provider_budget_state(provider TEXT PRIMARY KEY,day_key TEXT NOT NULL,month_key TEXT NOT NULL,daily_spend_usd REAL NOT NULL DEFAULT 0,monthly_spend_usd REAL NOT NULL DEFAULT 0,reserved_usd REAL NOT NULL DEFAULT 0,updated_at TEXT NOT NULL)`).run()}
export async function eligibleRoutes(env){await ensureRoutingSchema(env);try{const r=await env.DB.prepare(`SELECT pm.provider,pm.model_id,i.endpoint,i.key_cipher,i.iv,pm.qualified_free,i.verified_free FROM provider_models pm JOIN integrations i ON i.id=pm.provider LEFT JOIN provider_health ph ON ph.provider=pm.provider WHERE pm.qualified_free=1 AND pm.healthy=1 AND i.enabled=1 AND i.verified_free=1 AND COALESCE(ph.healthy,1)=1 LIMIT 30`).all();return r.results||[]}catch{return []}}
function withAttachments(messages,attachments=[]){if(!attachments.length)return messages;const list=messages.map(m=>({...m})),index=list.map(x=>x.role).lastIndexOf('user');if(index<0)return list;const original=String(list[index].content||''),parts=[{type:'text',text:original}];for(const a of attachments){if(a?.data&&/^image\//.test(a.type||''))parts.push({type:'image_url',image_url:{url:`data:${a.type};base64,${a.data}`}})}if(parts.length>1)list[index].content=parts;return list}
async function invoke(env,route,messages,mode,options={}){const key=await decryptStoredKey(env,route),safeMessages=guardedMessages(withAttachments(messages,options.attachments||[])),abort=signal(mode==='hard'?18000:9000);if(route.provider==='gemini'){if(!key)throw new Error('Gemini credential missing');const contents=safeMessages.map(m=>({role:m.role==='assistant'?'model':'user',parts:Array.isArray(m.content)?m.content.map(p=>p.type==='image_url'?{inlineData:{mimeType:String(p.image_url?.url||'').slice(5).split(';')[0],data:String(p.image_url?.url||'').split(',')[1]||''}}:{text:String(p.text||'')}):[{text:String(m.content||'')}]}));const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(route.model_id)}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents}),signal:abort});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.error?.message||`HTTP ${res.status}`);return {text:sanitize((data?.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('\n')),inputTokens:0,outputTokens:0}}const base=clean(route.endpoint||defaults[route.provider]);if(!base)throw new Error('Provider endpoint missing');const headers={'content-type':'application/json'};if(key)headers.Authorization=`Bearer ${key}`;if(route.provider==='openrouter'){headers['HTTP-Referer']='https://ai-hub-93x.pages.dev';headers['X-Title']='HOPE'}const body={model:route.model_id,messages:safeMessages,max_completion_tokens:mode==='hard'?4096:2048};if(route.provider==='openai'&&/^gpt-5/i.test(route.model_id))body.reasoning_effort=mode==='hard'?'high':mode==='fast'?'low':'medium';else body.temperature=mode==='hard'?0.2:0.6;const res=await fetch(`${base}/chat/completions`,{method:'POST',headers,body:JSON.stringify(body),signal:abort});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.error?.message||data?.error||`HTTP ${res.status}`);return {text:sanitize(data?.choices?.[0]?.message?.content||data?.choices?.[0]?.text||''),inputTokens:Number(data?.usage?.prompt_tokens||data?.usage?.input_tokens||0),outputTokens:Number(data?.usage?.completion_tokens||data?.usage?.output_tokens||0)}}
function promptFrom(messages){return [...(messages||[])].reverse().find(m=>m.role==='user')?.content||''}
function price(model,inputTokens=0,outputTokens=0){const p=OPENAI_PRICING[model];return p?((inputTokens*p.input)+(outputTokens*p.output))/1_000_000:0}
async function log(env,route,ok,latency,profile,error='',usage={}){try{await ensureLogs(env);const estimatedCostUsd=route.provider==='openai'?price(route.model_id,usage.inputTokens,usage.outputTokens):0;await env.DB.prepare(`INSERT INTO request_logs(provider,model,success,latency_ms,task_profile,error,estimated_cost_usd,input_tokens,output_tokens,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(route.provider,route.model_id,ok?1:0,latency,JSON.stringify(profile),String(error||'').slice(0,1000),estimatedCostUsd,Number(usage.inputTokens||0),Number(usage.outputTokens||0),new Date().toISOString()).run();if(ok&&route.provider==='openai')await env.DB.prepare(`UPDATE provider_settings SET last_success_at=?,last_error=NULL,updated_at=? WHERE provider='openai'`).bind(new Date().toISOString(),new Date().toISOString()).run()}catch{}}
async function ranked(env,messages){await ensureLogs(env);const prompt=promptFrom(messages),profile=taskProfile(prompt);let eligible=[];try{eligible=await eligibleRoutes(env)}catch{}let routes=[];try{routes=await rankedRoutes(env,eligible,prompt)}catch{}return {prompt,profile,routes}}
async function settleBudget(env,reservation,actual=0){if(!reservation)return;try{await env.DB.prepare(`UPDATE provider_budget_state SET reserved_usd=MAX(0,reserved_usd-?),daily_spend_usd=daily_spend_usd+?,monthly_spend_usd=monthly_spend_usd+?,updated_at=? WHERE provider=? AND day_key=? AND month_key=?`).bind(reservation.amount,actual,actual,new Date().toISOString(),reservation.provider,reservation.day,reservation.month).run()}catch{}}
async function runOne(env,route,messages,mode,profile,options={}){const started=Date.now();try{const output=await invoke(env,route,messages,mode,options),latencyMs=Date.now()-started,estimatedCostUsd=route.provider==='openai'?price(route.model_id,output.inputTokens,output.outputTokens):0;await log(env,route,true,latencyMs,profile,'',output);await settleBudget(env,options.budgetReservation,estimatedCostUsd);return {ok:true,provider:route.provider,model:route.model_id,text:output.text,latencyMs,score:route.intelligenceScore,usage:{inputTokens:output.inputTokens,outputTokens:output.outputTokens,estimatedCostUsd}}}catch(e){const latencyMs=Date.now()-started,error=String(e?.name==='TimeoutError'?`Timed out after ${mode==='hard'?'18':'9'}s`:e?.message||e);await log(env,route,false,latencyMs,profile,error);await settleBudget(env,options.budgetReservation,0);if(route.provider==='openai')try{await env.DB.prepare(`UPDATE provider_settings SET last_error=?,updated_at=? WHERE provider='openai'`).bind(error.slice(0,1000),new Date().toISOString()).run()}catch{}return {ok:false,provider:route.provider,model:route.model_id,error,latencyMs,score:route.intelligenceScore}}}

async function openAIBudget(env,mode,messages){await ensureLogs(env);await ensureBudgetSchema(env);const row=await env.DB.prepare(`SELECT i.*,s.daily_budget_usd,s.monthly_budget_usd,s.enabled setting_enabled,s.emergency_stop FROM integrations i JOIN provider_settings s ON s.provider=i.id LEFT JOIN provider_health h ON h.provider=i.id WHERE i.id='openai' AND i.enabled=1 AND s.enabled=1 AND s.emergency_stop=0 AND COALESCE(h.healthy,1)=1`).first().catch(()=>null);if(!row?.key_cipher)return {ok:false,error:'OpenAI production routing is not enabled.'};const model=String(row.model||OPENAI_AUTO_MODELS[mode]||OPENAI_AUTO_MODELS.normal),pricing=OPENAI_PRICING[model];if(!pricing)return {ok:false,error:'OpenAI model pricing is not configured; routing remains safely disabled.'};const now=new Date(),day=now.toISOString().slice(0,10),month=now.toISOString().slice(0,7),nowIso=now.toISOString(),dailyBudget=Number(row.daily_budget_usd||0),monthlyBudget=Number(row.monthly_budget_usd||0),inputEstimate=Math.max(1,Math.ceil(JSON.stringify(messages||[]).length/4)),outputCeiling=mode==='hard'?4096:2048,reserve=price(model,inputEstimate,outputCeiling);if(dailyBudget<=0||monthlyBudget<=0)return {ok:false,error:'OpenAI budgets are not configured.'};await env.DB.prepare(`INSERT INTO provider_budget_state(provider,day_key,month_key,daily_spend_usd,monthly_spend_usd,reserved_usd,updated_at) VALUES('openai',?,?,0,0,0,?) ON CONFLICT(provider) DO UPDATE SET daily_spend_usd=CASE WHEN day_key=excluded.day_key THEN daily_spend_usd ELSE 0 END,monthly_spend_usd=CASE WHEN month_key=excluded.month_key THEN monthly_spend_usd ELSE 0 END,reserved_usd=CASE WHEN day_key=excluded.day_key THEN reserved_usd ELSE 0 END,day_key=excluded.day_key,month_key=excluded.month_key,updated_at=excluded.updated_at`).bind(day,month,nowIso).run();const claimed=await env.DB.prepare(`UPDATE provider_budget_state SET reserved_usd=reserved_usd+?,updated_at=? WHERE provider='openai' AND day_key=? AND month_key=? AND daily_spend_usd+reserved_usd+?<=? AND monthly_spend_usd+reserved_usd+?<=?`).bind(reserve,nowIso,day,month,reserve,dailyBudget,reserve,monthlyBudget).run();if(Number(claimed?.meta?.changes||0)!==1)return {ok:false,error:'OpenAI budget guard reached.'};return {ok:true,route:{provider:'openai',model_id:model,endpoint:row.endpoint,key_cipher:row.key_cipher,iv:row.iv,intelligenceScore:100},reservation:{provider:'openai',amount:reserve,day,month}}}
export async function executeOpenAIPrimary(env,messages,mode='normal',options={}){try{const budget=await openAIBudget(env,mode,messages);if(!budget.ok)return {...budget,skipped:true};const profile=taskProfile(promptFrom(messages)),result=await runOne(env,budget.route,messages,mode,profile,{...options,budgetReservation:budget.reservation});return {...result,routing:{primary:true,provider:'openai',budgetReservedUsd:budget.reservation.amount}}}catch(e){return {ok:false,error:String(e?.message||e),skipped:true}}}
export async function executeZeroCost(env,messages,mode='normal',options={}){
  try{
    const {profile,routes}=await ranked(env,messages),chosen=routes.slice(0,3);
    if(!chosen.length)return {ok:false,error:'No qualified zero-cost route is currently available.',attempts:[],routing:{adaptive:true,parallel:true,profile,candidates:0}};
    const settled=await Promise.all(chosen.map(r=>runOne(env,r,messages,mode,profile,options)));
    const good=settled.filter(x=>x.ok).sort((a,b)=>a.latencyMs-b.latencyMs)[0];
    if(good)return {ok:true,provider:good.provider,model:good.model,text:good.text,attempts:settled.filter(x=>!x.ok),routing:{adaptive:true,parallel:true,profile,score:good.score,latencyMs:good.latencyMs,candidates:routes.length,raced:chosen.length}};
    return {ok:false,error:'No qualified zero-cost route could complete this request.',attempts:settled,routing:{adaptive:true,parallel:true,profile,candidates:routes.length,raced:chosen.length}};
  }catch(e){return {ok:false,error:'HOPE model routing is temporarily unavailable.',attempts:[{error:String(e?.message||e)}],routing:{adaptive:true,parallel:true,candidates:0}}}
}
export async function executeModelDuel(env,messages,mode='hard'){try{const {profile,routes}=await ranked(env,messages);const chosen=[];for(const r of routes){if(!chosen.length||chosen.every(x=>x.provider!==r.provider||x.model_id!==r.model_id))chosen.push(r);if(chosen.length===2)break}if(chosen.length<2)return {ok:false,error:'At least two qualified models are required for a live duel.',available:chosen.length};const results=[];for(const r of chosen)results.push(await runOne(env,r,messages,mode,profile));const good=results.filter(x=>x.ok);return {ok:good.length===2,results,profile,candidates:routes.length,error:good.length===2?null:'One or more duel models failed.'}}catch(e){return {ok:false,error:'Model duel is temporarily unavailable.',results:[],details:String(e?.message||e)}}}
