import {requireOwner} from '../../lib/auth.js';
import {encryptStoredKey,decryptStoredKey} from '../../lib/vault.js';
const json=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
async function ensure(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS tool_connectors(id TEXT PRIMARY KEY,label TEXT NOT NULL,key_cipher TEXT,iv TEXT,account TEXT,metadata TEXT,enabled INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL)`).run()}
async function row(env){await ensure(env);return env.DB.prepare(`SELECT * FROM tool_connectors WHERE id='github'`).first()}
async function gh(token,path){const r=await fetch(`https://api.github.com${path}`,{headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','User-Agent':'Universal-AI-Hub','X-GitHub-Api-Version':'2022-11-28'}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body?.message||`GitHub HTTP ${r.status}`);return body}
export async function onRequestGet({request,env}){const denied=await requireOwner(request,env);if(denied)return denied;try{const r=await row(env);if(!r)return json({ok:true,connected:false,oauthReady:!!(env.GITHUB_CLIENT_ID&&env.GITHUB_CLIENT_SECRET)});const token=await decryptStoredKey(env,{key_cipher:r.key_cipher,iv:r.iv});let user=null,repos=[];if(token){user=await gh(token,'/user');const list=await gh(token,'/user/repos?per_page=100&sort=updated&affiliation=owner,collaborator,organization_member');repos=(Array.isArray(list)?list:[]).map(x=>({id:x.id,full_name:x.full_name,private:x.private,default_branch:x.default_branch,permissions:x.permissions||{},html_url:x.html_url}));}return json({ok:true,connected:!!token,account:user?{login:user.login,name:user.name,avatar_url:user.avatar_url}:null,repositories:repos,oauthReady:!!(env.GITHUB_CLIENT_ID&&env.GITHUB_CLIENT_SECRET)})}catch(e){return json({ok:false,error:String(e?.message||e)},502)}}
export async function onRequestPost({request,env}){const denied=await requireOwner(request,env);if(denied)return denied;if(!env.HUB_MASTER_KEY)return json({ok:false,error:'HUB_MASTER_KEY missing'},500);try{await ensure(env);const b=await request.json();const token=String(b.token||'').trim();if(!token)return json({ok:false,error:'GitHub token required'},400);const user=await gh(token,'/user');const encrypted=await encryptStoredKey(env,token);const meta=JSON.stringify({method:'fine-grained-token'});await env.DB.prepare(`INSERT INTO tool_connectors(id,label,key_cipher,iv,account,metadata,enabled,updated_at) VALUES('github','GitHub',?,?,?,?,1,?) ON CONFLICT(id) DO UPDATE SET key_cipher=excluded.key_cipher,iv=excluded.iv,account=excluded.account,metadata=excluded.metadata,enabled=1,updated_at=excluded.updated_at`).bind(encrypted.cipher,encrypted.iv,user.login,meta,new Date().toISOString()).run();return json({ok:true,connected:true,account:{login:user.login,name:user.name}})}catch(e){return json({ok:false,error:String(e?.message||e)},502)}}
export async function onRequestDelete({request,env}){const denied=await requireOwner(request,env);if(denied)return denied;try{await ensure(env);await env.DB.prepare(`DELETE FROM tool_connectors WHERE id='github'`).run();return json({ok:true,connected:false})}catch(e){return json({ok:false,error:String(e?.message||e)},500)}}
