import {runMission} from '../../lib/hope6-mission-runner.js';
import {nextAfter} from '../../lib/automation-schedule.js';

const json=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
async function authorized(request,env){const expected=String(env.AUTOMATION_RUNNER_SECRET||'');return !!expected&&(request.headers.get('authorization')||'')===`Bearer ${expected}`}
async function ensure(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_hope_missions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,title TEXT NOT NULL,objective TEXT NOT NULL,schedule TEXT NOT NULL,recurrence TEXT,next_run_at TEXT,status TEXT NOT NULL DEFAULT 'active',approval_mode TEXT NOT NULL DEFAULT 'writes',enabled INTEGER NOT NULL DEFAULT 1,last_run_at TEXT,run_count INTEGER NOT NULL DEFAULT 0,failure_count INTEGER NOT NULL DEFAULT 0,last_result TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_hope_mission_runs(id TEXT PRIMARY KEY,mission_id TEXT NOT NULL,user_id TEXT NOT NULL,status TEXT NOT NULL,job TEXT NOT NULL,started_at TEXT NOT NULL,finished_at TEXT,FOREIGN KEY(mission_id) REFERENCES user_hope_missions(id))`).run()}
export async function onRequestPost({request,env}){
  if(!(await authorized(request,env)))return json({ok:false,error:'Unauthorized runner'},401);await ensure(env);const tick=now();
  const q=await env.DB.prepare(`SELECT * FROM user_hope_missions WHERE enabled=1 AND status='active' AND next_run_at IS NOT NULL AND next_run_at<=? ORDER BY next_run_at ASC LIMIT 10`).bind(tick).all(),results=[];
  for(const mission of q.results||[]){const runId=crypto.randomUUID(),started=now();try{const r=await runMission(env,mission),finished=now(),needsApproval=r.job.status==='awaiting_confirmation',next=needsApproval?mission.next_run_at:nextAfter(mission.recurrence,new Date(finished)),missionStatus=needsApproval?'awaiting_confirmation':(next?'active':'completed'),runFinished=needsApproval?null:finished;await env.DB.prepare(`INSERT INTO user_hope_mission_runs(id,mission_id,user_id,status,job,started_at,finished_at) VALUES(?,?,?,?,?,?,?)`).bind(runId,mission.id,mission.user_id,r.job.status,JSON.stringify(r.job).slice(0,250000),started,runFinished).run();await env.DB.prepare(`UPDATE user_hope_missions SET status=?,next_run_at=?,last_run_at=?,run_count=run_count+1,last_result=?,updated_at=? WHERE id=?`).bind(missionStatus,next,finished,JSON.stringify({runId,status:r.job.status,progress:r.progress,block:r.job.block||null}).slice(0,50000),finished,mission.id).run();results.push({id:mission.id,runId,ok:true,status:r.job.status,nextRunAt:next,block:r.job.block||null})}catch(e){const finished=now(),error=String(e?.message||e);await env.DB.prepare(`UPDATE user_hope_missions SET failure_count=failure_count+1,last_run_at=?,last_result=?,updated_at=? WHERE id=?`).bind(finished,JSON.stringify({runId,status:'failed',error}).slice(0,50000),finished,mission.id).run();results.push({id:mission.id,runId,ok:false,status:'failed',error})}}
  return json({ok:true,version:'HOPE 6.1',checkedAt:tick,due:(q.results||[]).length,results});
}
function now(){return new Date().toISOString()}
